### ISSUE TITLE
LOAD3DSMOKE has extra types (documentation)

### ISSUE THREAD

**Issue by obscureed** [firemodels/smv#1001]
Some small documentation issues:

The SMV User Guide has a description of the LOAD3DSMOKE command: 'Two types are supported, "soot mass fraction" or "HRRPUV".'

Other types are now supported, so please could they be added to the documentation? I just tried "LOAD3DSMOKE [newline]TEMPERATURE" in a .ssf file, and it worked. I haven't tried the other options visible in the GUI: "CARBON DIOXIDE DENSITY" or "SOOT/HRRPUV(experimental loading)". (What is that?)

I think "soot mass fraction" should now be "SOOT DENSITY".

Thanks.
Ed

**Comment by gforney** [comment]
I updated the LOAD3DSMOKE entry in the smokeview user's guide.  thanks for pointing it out

**Comment by obscureed** [comment]
Great, thanks. I'll close this issue -- I can wait to see the changes in the next standard release.
