### ISSUE TITLE
Segmentation fault on loading data

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/smv#1004]
This has been a difficult one to reproduce, so below is the smallest input file I could produce with the same error. When view the output in smokeview, loading any slice or smoke3d data immediately results in a segmentation fault with no other error information provided.

Removing any of the slices avoids the error and simplifying the meshes does too. Manually removing slice files from the *.smv file also avoids the error. I ran it through gdb and it crashed somewhere in the glut menu code, but I don't have the mingw build set up very well for debugging (this also happens on the officially released version) so I haven't gotten much further.

```fortran
&HEAD CHID='test' /

&TIME T_BEGIN=0.0, T_END=5.0 /
&DUMP NFRAMES=20 /

&MESH ID='A', IJK=170,15,25, XB=3.0,20.0,0.0,1.5,7.5,10.0 /
&MESH ID='B', IJK=20,20,25, XB=18.0,20.0,1.5,3.5,7.5,10.0 /
&MESH ID='C', IJK=75,76,25, XB=12.5,20.0,-7.6,0.0,7.5,10.0 /

&VENT ID='OpenBoundary', SURF_ID='OPEN' XB=12.5,20.0,-7.6,-7.6,7.5,10 /

&SLCF ID='a' PBZ=9.5 QUANTITY='PRESSURE' /
&SLCF ID='b', QUANTITY='VELOCITY', VECTOR=.TRUE., XB=14.5,15.4,0,0,7.5,9.5 /
&SLCF ID='c', QUANTITY='VELOCITY', VECTOR=.TRUE., XB=16.0,16.9,1.5,1.5,7.5,9.5 /
&SLCF ID='d', QUANTITY='VELOCITY', VECTOR=.TRUE., XB=9.8,10.7,0,0,7.5,9.5 /
&SLCF ID='e', QUANTITY='VELOCITY', VECTOR=.TRUE., XB=9.8,10.7,1.5,1.5,7.5,9.5 /
&SLCF ID='f', QUANTITY='VELOCITY', VECTOR=.TRUE., XB=3.9,4.8,0,0,7.5,9.5 /
&SLCF ID='g', QUANTITY='VELOCITY', VECTOR=.TRUE., XB=5.7,6.6,1.5,1.5,7.5,9.5 /
&SLCF ID='h', QUANTITY='VELOCITY', VECTOR=.TRUE., XB=19.9,19.9,2.2,3.1,7.5,9.5 /

&TAIL /
```

**Comment by gforney** [comment]
Ill take a look. Thanks for input file
Glenn

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing
A submenu was being referenced without having been built
thanks for the catch

**Comment by JakeOShannessy** [comment]
Thanks Glenn, looks like that's done the trick.

**Comment by gforney** [comment]
Good. Let me know if you see any more problems
