### ISSUE TITLE
Ability to control length of vectors and spacing

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/smv#1024]
Can we have the ability to scale vectors on the order of the model rather than on the data? So instead of the vectors length being based on the quantity value, we would be able to specify a constant length on all the vectors. 

It will also be very useful if we could control the spacing between the vectors to avoid having a cluster of vectors when you have an area with a finer mesh as seen in the image below

![93DBA860](https://user-images.githubusercontent.com/38315126/92596636-06240580-f29e-11ea-8b81-4540779aea8f.PNG)

**Comment by gforney** [comment]
Ill take a look

**Comment by gforney** [comment]
I added a "uniform spacing" checkbox and a "uniform length" checkbox to the slicefile bounds dialog box under the vector tab.  Note, the vector spacing will only be uniform if the mesh spacing of the coarser mesh is an integer multiple of the mesh spacing of the more refined mesh (vectors are only output at grid node locations)

update smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by adnannweilati** [comment]
Works perfectly. Thanks for the quick response.

**Comment by gforney** [comment]
Thanks for reporting back
