### ISSUE TITLE
Floating CVENT

### ISSUE THREAD

**Issue by mcgratta** [firemodels/smv#1069]
Run the attached case with one or the other MULT line. In the single mesh case (first MULT line), there is a CVENT that sits on the floor. In the multi-mesh case (second MULT line), the CVENT floats above the floor. I ran this using the linux smokeview.
```
&HEAD CHID='junk' /

&MESH XB=0.00,0.50,-0.125,0.125,0.00,0.25, IJK=50,25,25, MULT_ID='mesh' /
 MULT ID='mesh', DX=0.5, I_LOWER=12, I_UPPER=12 /  <--- Use this line and the orange patch sits on the floor
&MULT ID='mesh', DX=0.5, I_LOWER= 0, I_UPPER=29 /  <--- Use this line and the orange patch floats above the floor

&TIME T_END=0. /

&SURF ID='Tunnel Wall', DEFAULT=T, COLOR='GRAY' /

&SURF ID='PATCH', COLOR='ORANGE' /

&VENT XB=6.15,6.27,-0.060,0.060,0,0, XYZ=6.21,0.0,0.0, RADIUS=0.053, SURF_ID='PATCH', SPREAD_RATE=1.0 /

&TAIL /
```

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
should be fixed.  update your repo and rebuild (you only need to rebuild smokeview, not libraries) or download smokeview's here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

let me know if if there is still a problem

**Comment by mcgratta** [comment]
Works! Thanks.
