### ISSUE TITLE
Smokeview core dumps on this file

### ISSUE THREAD

**Issue by mcgratta** [firemodels/smv#1091]
[Region2.zip](https://github.com/firemodels/smv/files/5997103/Region2.zip)
This smv file core dumps with both my linux and Windows smokeview. The linux version was just compiled.

**Comment by gforney** [comment]
Ill take a look

**Comment by gforney** [comment]
update your repo - should be fixed .  I assume this case does not have any terrain otherwise there might still be a problem

**Comment by gforney** [comment]
fixed binaries are at
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by mcgratta** [comment]
Working, thanks.
