### ISSUE TITLE
GLMAT pressure solver 

### ISSUE THREAD

**Issue by tden033** [firemodels/smv#1144]
Hi,
I am trying to model the pressure drop in a long tunnel, so I selected the GLAMT pressure solver as suggested. The GLMAT solver requires the meshes are at a same refinement level, and I did so. Specifically, I used 6 meshes and tried 4 different refinement levels ( uniform cell with the size of 0.13m, 0.2m, 0.26m, 0.4m). The 0.2m and 0.26m schemes were found running well, however, I was informed of the following error when running with the 0.13m and 0.4m cells.
"GLMAT Setup Error : Meshes at different refinement levels unsupported."

This is weird because I didn't change anything but the cell size and have made sure the cells are of the same size. 
Also, when I increased the mesh quantity from 10 to 11, the same error occurs even with the 0.2 m cells.
So anyone had the same issue?
For your convenience,  the code is attached below.
Your help will be much appreciated. 
[fire.txt](https://github.com/firemodels/smv/files/6454970/fire.txt)

Regards
Tao

**Comment by marcosvanella** [comment]
I'm closing the issue here as this is the smokeview issue tracker and opening it on the fds side, here:

https://github.com/firemodels/fds/issues/9498

**Comment by tden033** [comment]
Hi Marco and Randy,
Thanks for the help.

Regards
Tao
