### ISSUE TITLE
smokeview.ini not having an effect

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/smv#1168]
Smokeview isn't using bounds from the smokeview.ini file.  If I run the attached case and load the smokeview file with the attached smokeview.ini I should see bounds of 0 to 1000 for temperature but just see the global bounds and the bounds dialog box only shows the global bounds.  If I rename the smokeview.ini to cover_4.ini and open the smokeview file, then I get bounds of 0 to 1000 for temperature.

This is on windows using SMV6.7.17-0-g45b228fe9-release.  This is also happening with the smokvview released with FDS 6.7.6.

[cover_4.txt](https://github.com/firemodels/smv/files/6815681/cover_4.txt)
[smokeview.txt](https://github.com/firemodels/smv/files/6815685/smokeview.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
try smokeview located here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by drjfloyd** [comment]
working now.
