### ISSUE TITLE
SHOWEXTREMEDATA 2nd and 3rd inputs in recorded ini file ignored by Smokeview 

### ISSUE THREAD

**Issue by andrea-paradiso** [firemodels/smv#1173]
ie if SHOWEXTREMEDATA is 101, both the lower and upper data are showed in the colorbar

**Comment by gforney** [comment]
Ill take a look

**Comment by gforney** [comment]
try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by andrea-paradiso** [comment]
Working now (checked on Linux platform). Thanks!

**Comment by gforney** [comment]
good.  thanks for reporting back
