### ISSUE TITLE
Segmentation fault with custom ticks

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/smv#1210]
After modifying the *.ini file to customize axis ticks, I get a segmentation fault when trying to open smokeview.

I've uploaded a very simple example that reproduces this behavior (on my machine). I'm using macOS and I get this with the binary of the most recent smokeview release, as well as with a build of the most recent commit.

The lines I added to the *.ini file are 587-589:
TICKS
0.0 0.0 0.0 1.0 0.0 0.0 2
0.2 -2 0 0 0 4.0

[custom_ticks.fds.txt](https://github.com/firemodels/smv/files/7212984/custom_ticks.fds.txt)
[custom_ticks.ini.txt](https://github.com/firemodels/smv/files/7212985/custom_ticks.ini.txt)
[custom_ticks.smv.txt](https://github.com/firemodels/smv/files/7212986/custom_ticks.smv.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
update your smv repo and rebuild smokeview or use smokeview posted at link below.  let me know if you still see a problem

you'll also need to edit the SHOWTICKS keyword in your ini file changing 0 to 1 (from hide to show)

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by ericvmueller** [comment]
That seems to have fixed it for me. Thanks!
