### ISSUE TITLE
Boundary file that crosses a mesh boundary

### ISSUE THREAD

**Issue by mcgratta** [firemodels/smv#1237]
Run the case in the fds repo called `Fires/box_burn_away1.fds`. Bring it up in Smokeview and look at the boundary file of `MASS FLUX`. As the obstruction disappears, I notice that the faces abutting the mesh boundary are not colored. I tried to find a setting to make it show but could not. Have we dealt with this before? Seems familiar.

**Comment by gforney** [comment]
it does seem familiar.  I'll take a look

**Comment by gforney** [comment]
I commented out the code that was causing the problem.  If the problem comes up again I'll take another look.  I'll close this for now
