### ISSUE TITLE
Split Colorbar

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/smv#1305]
Im trying to create a custom colorbar in smokeview that looks like this where the colorbar would split in 3 different locations. My aim is get the colorbar to show the following:
- Show Green for temperatures between 20 and 100
- Show Yellow for temperatures between 100 and 120
- Show Orange for temperatures between 120 and 160 
- Show Red for temperatures between 160 and 220

Is this even possible to do in smokeview? Any help is appreciated.
![New Colorbar](https://user-images.githubusercontent.com/38315126/161545095-6a5ea8e3-7bfe-4441-99fc-e2bc585eb6bc.png)

**Comment by rmcdermo** [comment]
Right now, no.  And I really don't want to derail other work unless this would be trivial for Glenn (up to him).

When I need something like this, I read in my SLCF files using slread.m (fds/Utilities/Matlab/scripts/slread.m).  Then I manipulate the colorbar in either Matlab or Python.

**Comment by gforney** [comment]
you can do what you want with the  colorbar editor in smokeview - select menu Dialogs>View>Edit Colorbar

a colorbar in smokeview is a table with 256 red green blue entries. each r/g/b enttry ranges from 0 to 255. 

the dialog lets you set the table index and the r/g/b values for that index.  ie you are defining a 3D path in RGB space. so for your colorbar you would set (index/color)


0 green
102 green 
103 yellow
128 yellow
129 orange
178 orange
179 red
255 red



where 102 ~= 255*(100-20)/(220-20) otherr numbers in first column were obtained similarly

you'll need to convert various colors above to rgb values

**Comment by adnannweilati** [comment]
Great thanks alot!

If anyone stumbled into this in the future, this is what needs to be added into the configuration file in the 3D SMOKE INFO section to get that colorbar:

Custom_Colorbar
 8 7
 0 0 180 0
 102 0 180 0
 103 255 255 0
 128 255 255 0
 129 250 140 0
 178 255 149 0
 179 255 0 0
 255 255 0 0

**Comment by gforney** [comment]
I updated the colorbar editing section of the smokeview user's guide - added an example of using the GCOLORBAR ini keyword for defining colorbars
https://drive.google.com/drive/folders/0B_wB1pJL2bFQUlJwMmNfaHlqME0?resourcekey=0-pcVXIwGiBTMcjYh8bX-WAQ&usp=sharing
