### ISSUE TITLE
Colourbar select contour not shown

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/smv#1315]
ab473b6b6b7ae60088913a60ceffb9c711debbde introduced a regression where the black select contour is not shown as part of the script in Verification/Visualization/colorbar.smv. These images are used in the SMV Verification Guide.

Before ab473b6b6b7ae60088913a60ceffb9c711debbde:
![colorbar_med](https://user-images.githubusercontent.com/1982652/164648231-6f50a487-d253-480c-9283-dbb6158f6a17.png)

After ab473b6b6b7ae60088913a60ceffb9c711debbde:
![colorbar_med](https://user-images.githubusercontent.com/1982652/164648109-db8f98f4-2ec2-4f8d-a099-8202056fc54a.png)

**Comment by gforney** [comment]
Ill take a look

**Comment by gforney** [comment]
should be fixed in smokeview posted here, I also posted changes to central smv repo.  thanks for pointing out the problem

**Comment by JakeOShannessy** [comment]
Thanks Glenn, looks fixed.
