### ISSUE TITLE
Escaping of quoted names in CSV results in prepended space

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/smv#1384]
Currently a name in a CSV file such as `"SmokeDetector"` is parsed as `␣SmokeDetector` with a space prepended. Possibly a result of the below not being trimmed.

https://github.com/firemodels/smv/blob/21dea90a94ff20e3ce7489746ec32453e43d5e5d/Source/shared/string_util.c#L106-L110

**Comment by gforney** [comment]
Jake
Can you upload an example that fails.
Thanks
Glenn

**Comment by JakeOShannessy** [comment]
Hi Glenn,

`Verification/Detectors/aspiration_detector.fds` is a valid example. Adding the code below as a diagnostic at readsmv.c:346 (at the end of ReadCSV):

```c
for(int j=0;j<csvfi->ncsvinfo;j++) {
    printf("  longlabel: >%s<\n", csvfi->csvinfo[j].label.longlabel);
  }
```

I get the following output:

```
  longlabel: >Time<
  longlabel: >HRR<
  longlabel: >Q_RADI<
  longlabel: >Q_CONV<
  longlabel: >Q_COND<
  longlabel: >Q_DIFF<
  longlabel: >Q_PRES<
  longlabel: >Q_PART<
  longlabel: >Q_ENTH<
  longlabel: >Q_TOTAL<
  longlabel: >MLR_AIR<
  longlabel: >MLR_PROPANE<
  longlabel: >MLR_PRODUCTS<
  longlabel: >ZONE_1<
  longlabel: >Time Step<
  longlabel: >Wall Time<
  longlabel: >Step Size<
  longlabel: >Simulation Time<
  longlabel: >CPU Time<
  longlabel: >Time<
  longlabel: > sp1<
  longlabel: > sp2<
  longlabel: > sp3<
  longlabel: > asp1<
```

As you can see for standard values (which generally don't have quotes) the output is trimmed, but not for named devices (which generally have quotes, e.g. "sp1".

**Comment by gforney** [comment]
Thanks.  Ill take a look

**Comment by JakeOShannessy** [comment]
Note that there is a call to `TrimFrontBack`, but it's result is not used to set the label. See below:

https://github.com/firemodels/smv/blob/21dea90a94ff20e3ce7489746ec32453e43d5e5d/Source/smokeview/readsmv.c#L252-L270

Changing the last line to `SetLabels(&(ci->label), buffptr, buffptr, unit);` would address it, but I'm not sure if that's overlooking a design choice.

**Comment by gforney** [comment]
update your smv repo and try now .  thanks for the catch.  let me know if you still see a problem

**Comment by JakeOShannessy** [comment]
Yes that's fixed it, thanks Glenn.
