### ISSUE TITLE
Smokeview crashes when opening the calculation results

### ISSUE THREAD

**Issue by mst-lyubimov** [firemodels/smv#1437]
The calculation of project in file test_small.txt completed successfully, but Smokeview cannot open the result. We use Windows version of FDS 6.7.9 and SMV 6.7.21.
We could not understand the reason for the failure, but found that the error disappears if change the name of the fuel.
FUEL name in this project contains symbol " (double quote). Without this symbol, Smokeview can open the result.

[test_small.txt](https://github.com/firemodels/smv/files/9611243/test_small.txt)

**Comment by mcgratta** [comment]
This is what appears in the .smv file
```
HoC
 1
   34800.00000

FUEL
 1
 Polyethylene " a
```
It is not a good idea to use a quotation mark in a character string. I'll leave it to Glenn to explain why exactly Smokeview does not like this string.

**Comment by gforney** [comment]
double quotes are used to enclose strings when the sting contains embedded blanks.  smokeview got confused.  it thought the quote was enclosing a string and was expecting a 2nd quote which it didn't find.

I've improved the logic parsing these strings so it should handle your case now.  Im in the middle of making other changes.  Im not aware of bugs with this smokeview but I would remove your quote and go back to the earlier smokeview if you run into problems (let me know tthough of any problems you encounter)
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by mcgratta** [comment]
All this being said, I would avoid using quotation marks within a character string. It seems to serve no purpose other to confuse parsing algorithms.

**Comment by gforney** [comment]
note for future reference.  this smokeview change will break cases where you have commas within a label 

the take away is that when creating labels you SHOULD NOT use commas or double quotes or other characters that meaning in other contexts
