### ISSUE TITLE
OBST IDs in SMV file

### ISSUE THREAD

**Issue by lu-kas** [firemodels/smv#1487]
Hi!

If I see it correctly, the IDs of OSBTs, which are defined in the FDS input file, are not incorporated in the SMV file. As we would like to address individual OBSTs via their given IDs, it would be great if this information could be included. Would that be possible? Thanks!

**Comment by mcgratta** [comment]
Do you want to click on the OBST in Smokeview and see its label? If so, I don't know if Smokeview can do that. Glenn will know better. In any event, I usually just  use a COLOR to identify one or two obstructions. Not the best, but works for simple things.

**Comment by gforney** [comment]
right click and select Dialogs>View>Examine Geometry

then select a blockage with the mouse.  This will highlight a blockage.  Do the contents of the dialog box show the ID that you are looking for?

**Comment by lu-kas** [comment]
Sorry, maybe I was not clear enough. I mean the actual content of the SMV file. 

Background: We use [fdsreader](https://github.com/FireDynamics/fdsreader) to analyse data. It reads the SMV file and then the actual data files. In order to get for example the boundary of an OBST I have to address it. It would make things way easier if this could be done via IDs, the same way as it works with SLCF.

**Comment by gforney** [comment]
so we are on the same page,could you post a simple input file and say what ID in the input file you would like to appear in the smv file

**Comment by lu-kas** [comment]
Sure. This is an example file, including multiple meshes:
```
&HEAD CHID='out_wall_id' TITLE='OBST ID'/
&TIME T_END=1.0 /

&MULT ID='mesh', DX=1, DY=0.8, I_UPPER=3, J_UPPER=5,/

&MESH IJK= 20,16,72 XB=-1.5,-0.5,-2,-1.2,-0.1000,3.5, MULT_ID='mesh' /

&MATL ID = 'wall', CONDUCTIVITY = 2.3, SPECIFIC_HEAT = 1, DENSITY = 2300./
&SURF ID = 'wall', MATL_ID = 'wall',THICKNESS = 0.2/

/floor
&OBST ID='floor' XB=-1,2,-1.2,2.4,-0.1,0, SURF_ID='wall'/

/ceiling
&OBST ID='ceiling' XB=-1,2,-1.2,2.4,3,3.2, SURF_ID='wall'/

/wall right
&OBST ID='wall_r' XB=-0.85,-0.8,-1,2.4,0,3, SURF_ID='wall'/

/wall front
&OBST ID='wall_f' XB=-1,2,-1.2,-1,0,3, SURF_ID='wall'/

/fire obst
&OBST ID='fire' XB= -0.3,1.1,0.4,1.7,0.4,0.45 /

&VENT XB=-0.3,1.1,0.4,1.7,0.45,0.45 SURF_ID='fire' /
&REAC FUEL='METHANE' /
&SURF ID='fire', HRRPUA=1000, COLOR='RED' /

&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=.TRUE./
&BNDF QUANTITY='BACK WALL TEMPERATURE', CELL_CENTERED=.TRUE./

&TAIL /
```

I would like to see the IDs `floor`, `ceiling`, etc. to be attached to the OBSTs defined in the SMV file.

**Comment by gforney** [comment]
note, if an OBST intersects or overlaps with multiple meshes, the same OBST label will appear in the smv file OBST entry for each of those mesh entries

**Comment by lu-kas** [comment]
Thanks, Glenn! 

I think this will do the trick.
