### ISSUE TITLE
Latest test bundle crashes

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#1530]
I tried the latest test bundle on a couple of different cases and it crashes on initial load.  The case is here:

/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Validation/UMD_Line_Burner/Test_pmi2/methane_dx_p3125cm.smv

This is the error I get.

<img width="1369" alt="Screen Shot 2023-03-02 at 8 33 09 AM" src="https://user-images.githubusercontent.com/4418497/222443618-0918ccd7-3e8e-4fef-b846-0275094210b8.png">

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
if this is still an issue, re-open and let me know
