### ISSUE TITLE
Texture map not being applied to bingeom

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#1560]
When I run this case using ZVALS (campfire3.fds), the texture_map works fine.

[campfire3.fds.txt](https://github.com/firemodels/smv/files/11366723/campfire3.fds.txt)

When I run the case by importing a bingeom file (created from the first run), the texture_map does not show when applied.

I am using latest available SMV.

[campfire3_bingeom.fds.txt](https://github.com/firemodels/smv/files/11366724/campfire3_bingeom.fds.txt)

**Comment by rmcdermo** [comment]
Per @marcosvanella I need to use TERRRAIN_IMAGE on MISC.

Think we need an example in the user guide.  That is where I go to see what lines to add.  Do we need IS_TERRAIN or not?  The user guide says yes.  This seems to work without it.  I would rather not need it.

**Comment by rmcdermo** [comment]
Glenn,
As Marcos noted, when I change from using texture map to TERRAIN_IMAGE the geometry and image show up in setup mode (T_END=0), no problem.  When I try to run a case (T_END=100.), then when I first open Smokeview I do not see the image.  I only see it after hitting "q" (I had no idea of this, Marcos seemed to guess it might work).  I think the setup and run behavior should be consistent.  Also, whatever "q" does to TERRAIN_IMAGE should be available through a dialog, like how are able to "show" a texture map.  Here are the input files and image again.

[save.fds.txt](https://github.com/firemodels/smv/files/11366997/save.fds.txt)

![campfire3](https://user-images.githubusercontent.com/4418497/235500111-b8f74643-b139-4ecc-b534-949967d0a880.png)

**Comment by marcosvanella** [comment]
If the terrain is read from VERTS and FACES in the &GEOM line we need IS_TERRAIN=T to let FDS know that it is just getting the top triangulation. If not it will give an open geometry error. For bingeom terrains the GEOM_TERRAIN type is read from the binary file so IS_TERRAIN is set to T at read time (redundant to add it in the &GEOM line).

**Comment by rmcdermo** [comment]
I think we could do this automatically.  First do, shoot z rays, and if ALL z rays come back with exactly 1 crossing, then internally set IS_TERRAIN=T

**Comment by gforney** [comment]
should I be using save.fds.txt  ?

**Comment by rmcdermo** [comment]
Yes, use save.fds

**Comment by gforney** [comment]
if a case has a texture, do you want smokeview to show it by default or have the user show it by hand if they want

**Comment by rmcdermo** [comment]
I don't have a strong opinion.  Intuitively, I would expect if I use TERRAIN_IMAGE that is would show up automatically (with option to hide via dialog).

**Comment by gforney** [comment]
smokeview that addresses some of the comments above posted here (or update your smv repo and rebuild smokeview)
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

comments addressed
1. will show texture map by default
2. initial view for TEND=0 and TEND>0.0 should be consistent
3. you can show/hide texture map from the Immersed geometry dialog box at:
Dialogs>View>Examine Geometry Immersed tab

note: slice files may be made partially transparent allowing one to see the underyling texture map.  this should also work for boundary files but does not - I''m working on it

let me know if I've missed something

**Comment by rmcdermo** [comment]
Glenn,
Seems to work now.  Thanks!

This case illustrates an interesting "feature" of the current texture map: it appears to be using an interpolation at the finest resolution.  Can we nix that?  I'd like to actually see the the discrete pixels if that is possible, something analogous to "CELL_CENTERED" colors.

<img width="925" alt="Screenshot 2023-05-05 at 3 17 32 PM" src="https://user-images.githubusercontent.com/4418497/236550633-35028c98-c60c-4b6b-b66d-70d336a9c913.png">
