### ISSUE TITLE
Keyboard shortcut for anti-aliasing still in popup help

### ISSUE THREAD

**Issue by obscureed** [firemodels/smv#1569]
In smokeview 6.8.0, the keyboard shortcut to toggle anti-aliasing has been removed. The keyboard shortcut used to be '&', but now this toggles something else, HVAC metro view mode. Looking in callbacks.c, I see that there is no longer any keyboard shortcut to toggle anti-aliasing. I calmed down about this when I realised that the new default setting is for nicer-looking lines anyway. (Is this still achieved with antialiasflag/SMOOTHLINES, or has something else changed?)

Anyway, my only comment is that in menus.c, '&' (or actually '&&') is still promised as a shortcut for anti-aliasing in the popup from rightclick...Help...Shortcuts. This can be removed now. This is a very minor tweak -- I don't think it needs a patched version etc.

Thanks for your efforts.
Ed

**Comment by gforney** [comment]
I added the & shortcut back (and changed HVAC metro view shortcut to ALT & ). try smokeview posted here (mac smokeview not updated yet, mac is currently offline)

the default value for this parameter is 1 - ie to smooth or antialias lines

https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

**Comment by obscureed** [comment]
Ah, OK, I've remembered what's happening: I want to turn antialiasing off every time -- It smooths out the lines by adding some background color to borderline pixels, and sometimes (often) it gets the background color wrong (understandably, because this is a complex depth calculation for every pixel). See the attached images. Really, I should set it up in ~/.smokeview.ini, and then I shouldn't need the shortcut -- but thanks for putting it back. (I have not tested the patch yet, but I will.)
Antialias on:
![antialias_on](https://user-images.githubusercontent.com/25529492/236537090-59c20a30-5d65-4fd3-9af6-d0e5eb7bb4c9.png)
Antialias off:
![antialias_off](https://user-images.githubusercontent.com/25529492/236537127-4059eaeb-c21a-43ab-8ae4-e8677d4f4002.png)

**Comment by obscureed** [comment]
Sorry, that was a bad comparison, because the second image was double-resolution. Here's a different view:
![wider_antialias_on](https://user-images.githubusercontent.com/25529492/236561521-1d4de565-8e70-4b54-893d-c6b3f6a0185d.png)
![wider_antialias_off](https://user-images.githubusercontent.com/25529492/236561536-8f2e5dfd-7ee5-493b-871b-6b30d02eae85.png)

**Comment by obscureed** [comment]
In the patched version of smokeview (SMV-6.8.0-110-gab3231e6d-master):
• The '&' keyboard shortcut is back to toggling antialiasflag -- thanks!
• The ALT-) keyboard shortcut does not seem to do anything.
— I tried it on a case with some HVAC elements -- see [clip-vectors_with-hvac.fds.txt](https://github.com/firemodels/smv/files/11409014/clip-vectors_with-hvac.fds.txt), clip-vectors_with-hvac.fds.txt in https://github.com/firemodels/smv/issues/1563 -- and a case with no HVAC elements. At least it did not crash the latter.
— I have not yet had time to learn what HVAC metro view mode should look like, but I was expecting a message about HVAC metro view mode to the bash terminal window.
• This issue was about the '&' shortcut, so I can close it. Thanks!

**Comment by gforney** [comment]
in the regular hvac network view ducts go directly from one node another that they are connected too.  in metro view  the ducts go horizontally and/or vertically NOT diagonaly to get from one hvac node to another as if the ducts were going along city streets.
