### ISSUE TITLE
SMV 6.4.2: Human speed- wrong colorbar

### ISSUE THREAD

**Issue by gjaeger** [firemodels/smv#165]
Smokeview 6.4.2-1-gf85fd7a
FDS 6.5.2 - Git-r21-0-g4e9103f; FDS+Evac 2.5.1

Problem:
Is there a bug to show the human speed colorbar in smokeview? _human_speed_ and _human_altered_with_data_ are activate. 

![exercise_01_0003](https://cloud.githubusercontent.com/assets/7759675/20919795/d77a3672-bb9d-11e6-925f-55eddcec7f35.png)

My inputfile: [exercise_01_fds.txt](https://github.com/firemodels/smv/files/633392/exercise_01_fds.txt)

The issue [#2021](https://github.com/firemodels/fds/issues/2021) already describes the same problem

**Comment by gforney** [comment]
I'll take a look at it

**Comment by gforney** [comment]
should be fixed in test smokeview 's posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by gjaeger** [comment]
It works with SMV 6.4.3-14-gd8475fb. Thanks.

You can close the issue.

**Comment by gforney** [comment]
Thanks for reporting back
