### ISSUE TITLE
smv crash with customized colorbar

### ISSUE THREAD

**Issue by ChristianKraft** [firemodels/smv#169]
Hello,

as I wrote in [https://groups.google.com/forum/#!topic/fds-smv/Cl70GioA_xE](url) smv crashes after adding a customized colorbar to the global smokeview.ini. The problem occurs with version 6.4.2 and may be earlier versions.

Here is what I did:

1.) Created a new colorbar in the  "customize colorbar" dialog by clicking "new colorbar" and "save settings". There were ne change of the colorbar for this test. 

![grafik](https://cloud.githubusercontent.com/assets/11407769/21183020/463bab22-c206-11e6-99b1-35e70ccbfa36.png)

2.) Copied the entry from the local ini file of the actual simulation to the global smokeview.ini.

```
 GCOLORBAR
  1
  Copy of Rainbow
  5 0
  0 0 0 255
  64 0 255 255
  128 0 255 0
  192 255 255 0
  255 255 0 0
```

[smokeview.ini.txt](https://github.com/firemodels/smv/files/651802/smokeview.ini.txt)

If I open a smv file, smokeview crashes while reading the local ini file. 

![grafik](https://cloud.githubusercontent.com/assets/11407769/21183435/3026275c-c208-11e6-9f5e-d15246448540.png)

![grafik](https://cloud.githubusercontent.com/assets/11407769/21183445/3bf58afa-c208-11e6-900b-6fd9ea4acc4e.png)

Thanks for help. Please let me know if you need more informations. 

Christian

**Comment by gforney** [comment]
I'll take a look at it

**Comment by gforney** [comment]
some variable were not being initialized when reading in a colorbar  from an .ini file.  try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by ChristianKraft** [comment]
Now it works! Thank you!

**Comment by gforney** [comment]
what is not working? it is working for me.  make sure you are using the latest smokeview.

**Comment by ChristianKraft** [comment]
It works. It was my mistake. I forgot to add a blank in front of every line after GCOLORBAR.

**Comment by gforney** [comment]
thanks for reporting back
