### ISSUE TITLE
smv_6.4.2_linux64.sh doesn't update the smv, however exits without error

### ISSUE THREAD

**Issue by akrasuski** [firemodels/smv#171]
The smv_6.4.2_linux64.sh doesn't work correctly. It informs that updating was successful however it doesn't perform any updating. There is also no information that something went wrong.

Do you wish to begin the update? (yes/no) y
Copying updated Smokeview files to /home/krasus/FDS/FDS6
Update complete.

Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gforney** [comment]
I will take a look at it

**Comment by gforney** [comment]
I went back and regenerated the 6.4.2 bundle for Linux.  That should work now also

**Comment by akrasuski** [comment]
Thank you very much, works perfectly.

**Comment by gforney** [comment]
Thanks for reporting back
