### ISSUE TITLE
Smokeview fails to open

### ISSUE THREAD

**Issue by pimzzff1** [firemodels/smv#1748]
Hello,

Whenever I open a .smv file in smokeview, it quits after the 'wrapping up' message. I've tried this for a few models, all give the same result (see image). An example is attached.  

The approach workstation I run my simulations on through RDP. The GPU is NVidea RTX A4500, drivers where recently updated (1 month ago).

Hoping you can help me out.
Best regards, Pim

![image](https://github.com/firemodels/smv/assets/60132385/412059c4-72a8-4d87-b004-b3930c0fd5d3)
[Auto_GRID0_05_FDS.txt](https://github.com/firemodels/smv/files/13457214/Auto_GRID0_05_FDS.txt)
[Auto_GRID0_05_SMV.txt](https://github.com/firemodels/smv/files/13457215/Auto_GRID0_05_SMV.txt)

**Comment by gforney** [comment]
Ill take a look. Upload the .fds input file also

Did you type smokevirw, then use the open file dialogue to ipen your case?
If so try typing
smokeview casename
where casename is the name of your case .

**Comment by pimzzff1** [comment]
Thanks for your reply. Indeed, that is what I did. Doing it as you've discribed does not change the issue:

![image](https://github.com/firemodels/smv/assets/60132385/e446627f-ac68-4d9b-9bc9-10fb9db266b0)

The .fds was included in my first post ([Auto_GRID0_05_FDS.txt])(https://github.com/firemodels/smv/files/13457214/Auto_GRID0_05_FDS.txt)

Thanks in advance, appreciate the help!

**Comment by gforney** [comment]
version 6.8.0 crashed for me too.  try smokeview posted at link below. this worked for me.  likely a bug was fixed between when 6.8.0 was released and now.  
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

**Comment by pimzzff1** [comment]
This version seems to work okay. Thanks for helping me!
