### ISSUE TITLE
vent not displayed

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/smv#1752]
The attached txt file is a smokeview file. On the floor of the compartment is a steel gas burner defined with OBST with a VENT ontop for the fire.  The OBST and VENT line are below and the grid resolution is 0.0508 (2 in) so the OBST and VENT are both grid alligned. Using:

Smokeview  Test - Nov 21 2023 - 09:33:11

Version          : Test
Revision         : SMV-6.8.0-1381-g1514945-nightly
Revision Date    : Mon Nov 20 13:40:02 2023 -0500
Compilation Date : Nov 21 2023 09:33:11
Compiler         : Intel DPC++/C++ 2023.1.0
Checksum(SHA1)   : bb1d3cccb6daf09129bb32c8169e212e9fae5480
Platform         : WIN64  (Intel C/C++)
Smokeview path   : C:\Program Files\firemodels\SMV6\smokeview.exe
Bin directory    : C:\Program Files\firemodels\SMV6\

I do not see the fire vent (which is colored RED). If I hide the OBST it is there. When I run the case FDS is adding fuel. 

&OBST ID='Burner', XB=-0.3556,0.3556,-0.3556,0.3556,0.0000,0.1524, SURF_ID='Burner'/
&VENT ID='Fire', SURF_ID='Fire', XB=-0.3048,0.3048,-0.3048,0.3048,0.1524,0.1524,IOR=3/

[as_built_open.txt](https://github.com/firemodels/smv/files/13477810/as_built_open.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
can you upload the .fds file from your case or create a case that has the OBST and VENT from your case.  for some reason smokeview is offsetting the vent in the wrong direction.  not sure what is different about your case

**Comment by gforney** [comment]
this might be an fds problem (or a problem with smokeview with how it is getting vent info from the .smv file).  I stripped out stuff  from the input file so it will run with FDS 6.8.0 and the vent is visible. I ran with a recent version of fds ( FDS-6.8.0-1053-g1c30aa4-master ) and the vent is not visible both with same version of smokeview.  I"ll git bisect to see if I can track down when things changed.  can you think of a change in fds that would affect how vent info is output to the .smv file?

**Comment by drjfloyd** [comment]
I can't think of anything offhand.

What did you have to strip out? This file runs for me as is with FDS 6.8.0.

**Comment by drjfloyd** [comment]
Weird. I get this with the release:

Fire Dynamics Simulator

 Current Date     : December  7, 2023  10:23:39
 Revision         : FDS-6.8.0-0-g886e009-release
 Revision Date    : Tue Apr 18 07:06:40 2023 -0400
 Compiler         : Intel ifort 2021.7.0
 Compilation Date : Tue 04/18/2023  03:22 PM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.10 for Windows* OS


 Job TITLE        :
 Job ID string    : as_built_open

 Time Step:      1, Simulation Time:      0.05 s

And this with a build from last week's source:

 Current Date     : December  7, 2023  10:30:30
 Revision         : FDS-6.8.0-1053-g1c30aa4-master
 Revision Date    : Fri Dec 1 17:11:50 2023 -0500
 Compiler         : Intel ifort 2021.10.0
 Compilation Date : Thu 12/07/2023  10:25 AM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.10 for Windows* OS


 Job TITLE        :
 Job ID string    : as_built_open

 Time Step:      1, Simulation Time:      0.05 s

**Comment by gforney** [comment]
my bad.  I read the version wrong.  I had an older version of fds installed

**Comment by gforney** [comment]
should be fixed.  update your smv repo and rebuild smokeview or try smokeview posted at link below.  

I made some changes recently to allow vents to be displayed properly on thin surfaces. fds outputted IOR info for smokeview to use to do this .  I reversed a sign. (interpreted an IOR=3 as if it was -3 and vice versa)
 
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

**Comment by gforney** [comment]
are you still seeing the problem?
