### ISSUE TITLE
smokevie question

### ISSUE THREAD

**Issue by zhangyijia405** [firemodels/smv#1815]
I'm using a Linux system, and there is no smv file generation during the fds calculation, but the smv file is generated after the calculation is completed, which makes it impossible for me to see the animation of the simulation halfway, is this normal

**Comment by rmcdermo** [comment]
This depends on your system configuration.  You need to discuss with your administrator.  Closing this issue.  If you wish to continue, start a Discussion.

**Comment by rmcdermo** [comment]
So, you need to contact the admin of the cloud platform.  This is a configuration issue on their end.

**Comment by zhangyijia405** [comment]
Ok, I see, thank you for your reply
