### ISSUE TITLE
smokeview problem with the loading of Isosurface 

### ISSUE THREAD

**Issue by soroush-95** [firemodels/smv#1819]
Hi, 

**Describe the bug**
I'm running some pool fire cases and I have an Iso-surface command as following: 

&ISOF QUANTITY='HRRPUV' , VALUE(1)=200, QUANTITY2='TEMPERATURE' /

However, when trying to load it via smokeview. I receive an error and it immediately closes. 
The error is as following: 

Loading NIST_Methanol_1_1.iso(hrrpuv)Expected record of 1 bytes, found one of 4 bytes
Expected record of 4 bytes, found one of 16777216 bytes
Expected record of 1 bytes, found one of 4 bytes

**To Reproduce**

As far as I can tell, it's any case that has an ISOF command with two quantities 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version: I tried with both SMV-6.8.0-0-gd02fd68-release and SMV-6.8.0-2078-g8d2226f-test 
 
BR,
Soroush

**Comment by gforney** [comment]
try the latest test smokeview  at 
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

you can set the temperature bounds using the File/Data/Coloring dialog box - Isosurface tab.  It is not displaying a colorbar.  I'm looking at that problem

**Comment by gforney** [comment]
try smokeview ((SMV-6.8.0-2141-gd720461_xxx) posted here
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

for now, the script that builds test smokeview's uploads to the same location as the nightly bundle script .  I don't have time to fix this now. so these smokeview test bundles will be over written tomorrow morning (ie have a different name). Let me know if you don't download them in time and I"ll upload another copy

post a test case if it doesn't work and let me now how it fails

**Comment by gforney** [comment]
is the case working for you now with the latest nightly build?

**Comment by gforney** [comment]
if it is still not working - reopen the issue and provide details of what is going wrong

**Comment by soroush-95** [comment]
Hi, 

Apologies for delayed response. 
Thanks alot. The issue is fixed with the latest version of smokeview.

Best, 
Soroush
