### ISSUE TITLE
Temperature slice colobar retains level set color bar if loaded after level set slice

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#1832]
Try this simple test case.

[test.fds.txt](https://github.com/firemodels/smv/files/14575181/test.fds.txt)

If you first load the slice of level set, then temperature, the temperature slice retains the colorbar for level set.  If you load temperature first, it works correctly the first time.  But then fails again if you try to go back to temperature after loading level set.

![Screenshot 2024-03-12 at 11 46 20 AM](https://github.com/firemodels/smv/assets/4418497/e5626c8f-3721-4de6-a32c-0a242c9ba2b8)

![Screenshot 2024-03-12 at 11 46 31 AM](https://github.com/firemodels/smv/assets/4418497/268b6181-d2ec-4fc5-8a16-a7fd12252704)

![Screenshot 2024-03-12 at 11 46 41 AM](https://github.com/firemodels/smv/assets/4418497/a3341b39-522b-4574-a54a-90394308c439)

**Comment by gforney** [comment]
I'll take a look.

**Comment by gforney** [comment]
I reproduced the case

**Comment by gforney** [comment]
colorbar issue should be fixed in smokeview posted here
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST
(2150 or later in name).  let me know if there is still an issue

**Comment by rmcdermo** [comment]
Seems to be fixed with

https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST2
