### ISSUE TITLE
GEOM BNDF not showing correct bounds

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#1833]
Please have a look at this case with your debugger and see what the BNDF (geometry) thinks the bounds ought to be.

[test_geom_bndf.fds.txt](https://github.com/firemodels/smv/files/14577212/test_geom_bndf.fds.txt)

When I load BNDF (geometry) I get this.  There are couple issues.  First, the colorbar limits seem to not be getting the right significant digits.  I am not sure what values ought to be (the HRRPUA is buried in the LS4 code).  But if you look at the HRRPUV the flame is visible (see next image).  The second issue is that the triangles look odd and we seem to have the age old problem of the boundary and the geometry overlapping each other.  But when we have a boundary quantity, we should not see the geometry bleeding through.  Lastly, I do not understand the triangles that get drawn when I view the geometry.   You can see from the input file, I am just drawing 2 triangles, which is what I would expect to see when I look at the "outline" view.

![Screenshot 2024-03-12 at 2 38 16 PM](https://github.com/firemodels/smv/assets/4418497/243a4bc8-06e0-4106-98b5-380246237135)

![Screenshot 2024-03-12 at 2 44 18 PM](https://github.com/firemodels/smv/assets/4418497/d18a500f-35ae-4e49-8496-581fb6be0d5b)

![Screenshot 2024-03-12 at 2 38 35 PM](https://github.com/firemodels/smv/assets/4418497/00d9c2f4-0ef6-45e1-897a-39a6a37c7480)

**Comment by rmcdermo** [comment]
This seems to have been related to Smokeview trying to read other bounds files.  Once I did a git clean in my directory and reran the case, the bounds, at least, look reasonable.  I'd still appreciate a look the other questions when you have time.

![Screenshot 2024-03-12 at 4 04 01 PM](https://github.com/firemodels/smv/assets/4418497/ee6ea202-d51b-4b38-a07d-c113e3b2c0ad)

**Comment by gforney** [comment]
the "odd" blue triangles may be in the data.   I hid the geometry after loading the geometry boundary file and still see the triangles.  also if geometry was overlapping boundary file I would have expect to see "hashing/thrashing" where geometry and boundary file was randomly visible.

press 'q' key to toggle geometry .  then you'll see the 2 triangles

**Comment by rmcdermo** [comment]
The blue triangles seem to be correlated with the black lines that are strange to me.  @marcosvanella Do you see what might be going on here?

When I toggle "q", I see these two images.  I don't understand the one on the right.  Where do the long black lines come from?  I would expect the one diagonal plus the cutfaces that are created by the intersection of the Cartesian cells and the geom.

<img src=https://github.com/firemodels/smv/assets/4418497/96196669-6b8f-4c2b-8ebf-1d888ac3088d width='400'>

<img src=https://github.com/firemodels/smv/assets/4418497/914b2f45-500d-419e-911f-f335dd01f875 width='400'>

**Comment by rmcdermo** [comment]
Yes, I see that now.  

![Screenshot 2024-03-13 at 11 05 16 AM](https://github.com/firemodels/smv/assets/4418497/ba01f0bc-2538-445d-b430-8a7dd0b683f1)

**Comment by marcosvanella** [comment]
Looking into this.

**Comment by marcosvanella** [comment]
Update repo and test.

**Comment by rmcdermo** [comment]
This all seems to be sorted now.  Any issues with cell linking are being tracked in a separate FDS Issue.
