### ISSUE TITLE
CFAST Visualization possible temperature colorbar error

### ISSUE THREAD

**Issue by firemist** [firemodels/smv#1840]
This is Smokeview build 2154:
![image](https://github.com/firemodels/smv/assets/25644607/703cf968-b95b-4057-8e23-76b98fbe6945)

On the colorbar in F, I saw an unexpectedly low number, so as test, I set the global minimum to 20 C:
![image](https://github.com/firemodels/smv/assets/25644607/d117297a-dbb6-4af8-8dd8-22c08ed839fe)

With the selected units as C, it looks fine:
![image](https://github.com/firemodels/smv/assets/25644607/ecc247e5-080b-4e7f-b60a-0c2fe0cb4055)

But switching the units to F, it gives an unexpectedly low (and non-physical) value:
![image](https://github.com/firemodels/smv/assets/25644607/8c749bd4-0099-4aac-b6dd-3f0bc4eb2f3c)

Switching to K, these values match the F values:
![image](https://github.com/firemodels/smv/assets/25644607/331cc8a2-bf8f-476d-bc39-ed1d466b2002)

So, in the conversion, it appears that Smokeview is erroneously subtracting 100 C somewhere in the Fahrenheit conversion. It somehow appears to be deducting 118 C in the conversion to Kelvin. Here is a table depicting what I found:
Displayed Values:			
	C	K	F
Max	1200	1355	1980
Min	20	175.1	-144.4
			
What should be displayed:			
Max	1200	1473	2192
Min	20	293	68
			
Differences:			
Max	0	-118	-212
Min	0	-117.9	-212.4

I apologize that my table does not look so nice.

In between these displays, I made no changes to anything. I did not move the displayed timestep, did not reread data, or anything other than using the option to switch the displayed temperature units.

Thank you for your assistance.

**Comment by gforney** [comment]
Thanks for the report. Ill take a look

**Comment by gforney** [comment]
can you uppload the input file you were using

**Comment by firemist** [comment]
OK, so here's the file. And here's some additional testing information:

I reran this on my local drive and had both the slice files and zone files written out to the directory.

This piece of information, hopefully, will help you look for the problem. The temperature error only appears to occur on the zone file temperature colorbar. While looking at the slice files, the colorbar works correctly changing between units.

Here's the file with the .in change to .txt for upload compatability.

[test_01.txt](https://github.com/firemodels/smv/files/14624157/test_01.txt)

Thanks for looking at this.

**Comment by gforney** [comment]
try smokeview posted at URL below.  this was an array indexing problem.  the colorbar labels were computed correctly they were just displayed in the wrong location (one row to high)
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST2

**Comment by firemist** [comment]
That took care of the temperature issue. Thank you very much.

One question I had about something that apparently changed between the CFAST distribution version of Smokeview and this version. In the distribution version, wall vents have a sort of depth. In other words, instead of being drawn as rectangles, they were drawn as parallelepipeds. I quite liked that presentation and thought it made them easier to see.

My first question is that I'm curious why that functionality was removed?
Secondly, is that a feature request that could come back?
If you want me to close this comment and make the request separate, just let me know and I'll submit it that way.
If it's not something that can be reasonably implemented, you can just close this thread with your response.

Thanks again!

**Comment by gforney** [comment]
If we took the parallelepiped vent feature out on purpose, i dont remember
why. Ill take a look at putting it back

**Comment by mcgratta** [comment]
We took those vents out on purpose. Don't put them back

**Comment by firemist** [comment]
Just to clarify, I'm not talking about the old default vents that used to be put in by CEdit added into the actual model. I was just talking about how the explicit vents are visualized in Smokeview. So, it's not a matter of putting vents in or out of the model, it's just how they're drawn in smoke view. I was asking about changing the way explicit vents, defined on the Wall Vents tab, are visualized in Smokeview back to the way they were shown in the CFAST distribution version of Smokeview that gave the vents a little bit of thickness making them more visible. That's why your comment about taking vents out has confused me.

Thank you.

**Comment by mcgratta** [comment]
The way that the vents were drawn in 3D caused some users to be confused, especially when the compartments had unusual dimensions. We thought it best to simple draw a vent as a plane, which is how one specifies it.

**Comment by firemist** [comment]
Thanks for the explanation. Thanks for all of your combined work.
