### ISSUE TITLE
Devices look huge in OSX

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/smv#1863]
Glenn, run this case a bit and open smv. For some reason the device in the middle (yellow) is so large that it looks like an obstacle.
Is there a reason we want them so large? Thanks.

<img width="1355" alt="Screenshot 2024-04-05 at 12 39 36 PM" src="https://github.com/firemodels/smv/assets/7450069/f4874856-3d1c-4226-a085-063007e2c473">

[auto_ignitionb.fds.txt](https://github.com/firemodels/smv/files/14888001/auto_ignitionb.fds.txt)

**Comment by gforney** [comment]
just saw this.  I'll take a look

**Comment by marcosvanella** [comment]
closing this, was missing the path to config for smv.
