### ISSUE TITLE
GEOMETRY COLOR overridden by SURF color in SMV

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/smv#1869]
Glenn, try this case. I checked that GEOMETRY(1)%RGB=[0 0 0] in fds. I don't see a black geometry, it is using the WALL color (red). It is dumping the right G%RGB in LU_SMV in line 1635 of dump.f90.
Note the default values for G%RGB are -1 (GEOMETRY_TYPE in type.f90).

 
#Title
&HEAD CHID='color', TITLE='color' /
#Mesh
&MESH XB= 0.0, 70.0, 0.0, 50.0, 0.0, 9.0, IJK= 70, 50, 36 /

#Time
&TIME T_END=0. /
#Obstructions
&SURF ID='WALL', RGB=255,0,0 /
&GEOM ID='Outside_Wall', SURF_ID='WALL',
VERTS=24.0, 15.0, 0.0,
24.0, 15.0, 3.5,
54.0, 30.0, 3.5,
54.0, 30.0, 0.0
POLY=1, 2, 3, 4,
EXTRUDE=10.0
COLOR='BLACK' /

&TAIL /

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
i think you said this was working now.  reopen if there is still a problem
