### ISSUE TITLE
Add time stamp to global min/max for slices

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#187]
Glenn,

I would be handy to know the time stamp when we see a high or low value for something in a slice file.  Right now when we toggle "research mode" we get something like this:

After slice file load: 
nblocks=6335 sizeblocks=174507158
 global min (slice file): 19.999962 cell=(48,1,6)
 global max (slice file): 3465.767822 cell=(62,1,35)

for a given mesh.  This value of 3500 C for temp is obviously bad, but I can't actually find it in the slice movie.  I think having the time stamp would help me track it down.

Thanks!
Randy

**Comment by gforney** [comment]
think you already told me that this is working now - if now let me know

**Comment by rmcdermo** [comment]
Yes, it was working.
