### ISSUE TITLE
Loading multiple SMV results to compare

### ISSUE THREAD

**Issue by AlanZandie** [firemodels/smv#1889]
Good day,

I wondered how can I get multiple contours or animations of results in one smokeview screen. I have attached a screenshot of how I mean, I believe there is a way to load different SMV results to better compare them. Kindly let me know where can I find the code to that, or if not too much trouble, could you please write for me here?

Thank you

![image](https://github.com/firemodels/smv/assets/93418696/5c5444ae-b6ae-4181-be24-6b8c005bbdc7)

**Comment by AlanZandie** [comment]
FYI, I am using the code below, but it is not working.
smokediff -smv -nb -np -s1 "C:\Users\MohammadZandie\Downloads\A\12-46N-Case1s" -s2 "C:\Users\MohammadZandie\Downloads\A\12-46N-Case2s" -d "C:\Users\MohammadZandie\Downloads\A\results" 25-100N-Case1s 25-100N-Case2s

**Comment by gforney** [comment]
Smokeview is not designed to view 2 or more cases at the same time. Smokediff is designed to compute the difference of two cases so that you can see the effect of some change.  You would then view the differenced files as one new case in smokeview
