### ISSUE TITLE
Hot key 'u' does not reload HRRPUV 3D smoke data

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#1909]
I am working with this case `fds/Validation/Wasson_Impinging_Plumes/FDS_Input_Files/wasson_50kW_1m_50mm.fds` and seeing some weird behavior with the latest smv (SMV-6.9.3-127-g9fea07bea-nightly).  First, when I load 3D hrrpuv, I notice that some (rhoC) data gets loaded, which I don't understand, because I am only asking for hrrpuv.  But then when I try to 'reload' using 'u' all that happens is the scene changes to include the smoke, which I am not asking for.  Please see if you can reproduce this on your end.  This is happening while the case is running, and I should mention that this case uses a `'RESULTS_DIR'` on `DUMP`.  Thanks

![](https://github.com/firemodels/smv/assets/4418497/020717a8-cb64-418e-9836-691ef8e3979b)

![](https://github.com/firemodels/smv/assets/4418497/58e13aa9-322d-4cce-89f5-a58cc979d515)

**Comment by gforney** [comment]
Ill take a look

**Comment by gforney** [comment]
think this was working but if not let me know and reopen
