### ISSUE TITLE
SMV Crashes when loading many slices, possible memory cap

### ISSUE THREAD

**Issue by LuisRobles1** [firemodels/smv#1918]
I am experiencing issues loading ~2600 visibility slices in SMV. Smokeview closes during loading the slices without presenting any error messages. I am able to view the slices after running SMOKEZIP then loading the compressed slices, but my ultimate goal is to view the time-averaged slices however the SMV console window does not indicate that the compressed slices are being time-averaged. I have also tried loading the uncompressed slices over a shorter time interval and over a smaller "spatial bounds" in order to overcome what appears to be a memory overload issue. 

I have tried the following SMV versions with no success, the results are from FDS 6.7.5:
- SMV-6.9.3-0-gc9109b6-release
- SMV-6.7.21-0-gccbc561da-release
- SMV-6.7.15-0-g4fa68dd74-release

**My questions are:**
- Is there a known cap of slices or memory that SMV is able to handle?
- Is time-averaging incompatible with the SMOKEZIP compressed slices. Similarly is the time-averaging incompatible with "spatial bounds" or "time bounds"
- I would appreciate any workarounds. 

The statistics of my fds results are as follows, unfortunately I am unable to share the FDS files or results due to NDA.
- I have 3,180 total .sf files totaling about 278MB, compressing them using SMOKEZIP brings the total to 40.4MB.
- I have 2642 visibility slices in the FDS file with a DT_SLCF of 1.0s
- 23 meshes run for 522 seconds

**Comment by gforney** [comment]
Upload your input file and ill rake a look
