### ISSUE TITLE
Clarify location of the global ini file

### ISSUE THREAD

**Issue by mcgratta** [firemodels/smv#2010]
I installed the latest test version of Smokeview from the nightly builds for Windows. The green spheres that indicate the location of sensors has reverted back to the default yellow cubes. I'm not sure where the global ini file is, or from where I was getting it previously. 

![image](https://github.com/user-attachments/assets/ec392c84-9bee-491d-83a7-97d114ae12d5)

Could you indicate in the start-up text where this global file is located, or if a local version is being used instead.

![image](https://github.com/user-attachments/assets/4aefbc6b-e568-43bb-9427-60855c6d15b0)

**Comment by JakeOShannessy** [comment]
This is a bug with whether or not the bin directory has a trailing slash or not. I know where the issue is.

**Comment by JakeOShannessy** [comment]
Addressed in #2011.

**Comment by gforney** [comment]
thanks, I'll run smokebot to make sure things are ok then merge

**Comment by gforney** [comment]
update your repo and try again.  I merge jake's PR to correct bin directory path and I pushed up changes to output ini path locations

**Comment by mcgratta** [comment]
This works! Thanks.
