### ISSUE TITLE
Scripting options

### ISSUE THREAD

**Issue by Vojta-Salek** [firemodels/smv#2024]
Hello,

I have recently tried to create some scripts using Smokeview 6.9.3. 

Is it somehow possible to: 
1) hide all surfaces,
2) flip the background,
3) increase the font size of colorbar labels and ticks,

using any of the script commands? I haven't found such options in the Script Glossary (Smokeview User's Guide, Sec. 9.3). I also tried some commands from Appendix D.3, but without success. When trying to perform these actions manually while recording the script, they were not added to the .ssf file.

Thank you very much for any help.

Vojtech Salek

**Comment by gforney** [comment]
set the scene the way you want. 
create an .ini file.
change its name if you want.
load the ini file in your script file using 
LOADINIFILE
  name_of_ini_file

**Comment by Vojta-Salek** [comment]
It works perfectly, thank you very much for your help!

**Comment by gforney** [comment]
great.  there arn't script keywords for every smokeview feature.  this is the "backdoor" way of scripting smokeview behavior. I"ll go ahead and close the issue.  you can reopen it if you encounter problems.
