### ISSUE TITLE
boundary file 'patches' not showing up for some surfaces

### ISSUE THREAD

**Issue by gforney** [firemodels/smv#2046]
smokeview is not drawing boundary file data on the black and red surfaces of the attached image.  these surfaces are on mesh boundaries which may be what is confusing smokeview

![PMMA_60_kW_2_cm_grid_0077](https://github.com/user-attachments/assets/e55e2ee6-e58e-4e42-a7ea-7cfd35c23d83)

The input file is at fds/Validation/NIST_NRC_Parallel_Panels/Current_Results/PMMA_60_kW_1_cm.fds in the fds repo and is attached:
[PMMA_60_kW_2_cm_grid.txt](https://github.com/user-attachments/files/17213822/PMMA_60_kW_2_cm_grid.txt)

**Comment by gforney** [comment]
problem occurs for the attached 3 mesh test case (same as earlier case using I_LOWER=3, I_UPPER=3, J_UPPER=2, K_LOWER=5 K_UPPER=5 on MULT line and changing boundary conditions to simple OPEN )

[PMMA_60_kW_2_cm_grid.txt](https://github.com/user-attachments/files/17215080/PMMA_60_kW_2_cm_grid.txt)

**Comment by gforney** [comment]
should be fixed.  my changes didn't help with boundary display on disappearing blockages though .  update your smv repo and rebuild Smokeview

**Comment by mcgratta** [comment]
I can now see the boundary data on all surfaces, but I also see the solid color of the surface itself interfering with the contour plot. This only appears at mesh boundaries.

**Comment by gforney** [comment]
update your smv repo and rebuild smokeview.  let me know if you still the problem (and problems with disappearing blockages)

**Comment by mcgratta** [comment]
Works under linux! Thanks.
