### ISSUE TITLE
Exterior surface shown on removable door

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#2053]
I am not sure what the expected behavior is for this case.  So, maybe @drjfloyd or @mcgratta can confirm.

When I run this case (latest smv test bundle):

[opening_ulmat.fds.txt](https://github.com/user-attachments/files/17259112/opening_ulmat.fds.txt)

and look at the box from an exterior angle for the door, the door appears to cover the outside.  If looking from the interior side, the behavior is as expected.  The door is later removed and things look like I would expect (no door from either angle).

![Screenshot 2024-10-04 at 9 29 19 AM](https://github.com/user-attachments/assets/2dcadd15-7858-485f-9acb-ad5d56acea48)

![Screenshot 2024-10-04 at 9 29 26 AM](https://github.com/user-attachments/assets/9ba85083-72d2-4c04-947e-4d3a76b5aa47)

**Comment by rmcdermo** [comment]
I guess the more I think about this, the more I can see maybe this is intended: we show the OBST covering the OPEN boundary, but we do not show the exterior wall.  If this is correct, then just close this.  Thanks

**Comment by rmcdermo** [comment]
Well, this gets more interesting with multiple meshes.  With the attached input file, the door does not seem to be removed in SMV, though the fluid solver seems to think the zones are now connected (0 and 1 on the left mesh).

[opening_ulmat.fds.txt](https://github.com/user-attachments/files/17259433/opening_ulmat.fds.txt)

![Screenshot 2024-10-04 at 9 42 37 AM](https://github.com/user-attachments/assets/4cc5ff6f-5e1d-4957-907d-12f06988b52f)

**Comment by drjfloyd** [comment]
Smokeview should not show a VENT on an MESH boundary for the domain when that boundary is between the eye and the inside of the domain. 

If you run with T_END = 0 to just generate an smv file, Smokeview should show all OBST as CTRL/DEVC logic is not evaluated in that case.
If you run with time stepping then Smokeview should show all active OBST.

If the first two images in the first post are before and after an OBST is removed, then that is the expected behavior.

The last two images of side-by-side meshes doesn not look correct.

**Comment by rmcdermo** [comment]
My last post might have something to do with my code versus the master or intel compiler versus gnu.  Let me track that down.

**Comment by drjfloyd** [comment]
On my PC running a recent smokeview test bundle the door disappears.

**Comment by gforney** [comment]
I'm working on a couple of issues that may be related
https://github.com/firemodels/smv/issues/2046
https://github.com/firemodels/smv/issues/1915
I may have a fix for the 2046 issue.  I'm testing with smokebot now.  I'll see if it makes a difference for your case in this issue

**Comment by rmcdermo** [comment]
The door disappears for me too in all cases.  Seems my problem was NFS related and the files were not updating as fast as I thought they should.

I do still see the door on the boundary as in the first post.  That door is due to an OBST, not just a vent, so I am still not clear on whether this is expected or not.

**Comment by drjfloyd** [comment]
Active OBST are always displayed.

**Comment by rmcdermo** [comment]
OK, I think this can be closed.  Sorry for the diversion.
