### ISSUE TITLE
Some boundary patches do not show

### ISSUE THREAD

**Issue by mcgratta** [firemodels/smv#2096]
[wall_10_cm.txt](https://github.com/user-attachments/files/17983461/wall_10_cm.txt)

Run this case a few time steps and then open in Smokeview. I'm not sure why the bottom and left boundaries appear to be open.

**Comment by gforney** [comment]
whacka mole - I'll take a look

**Comment by mcgratta** [comment]
The codes sent by FDS for the vents look OK.

**Comment by gforney** [comment]
update your smv repo and rebuild smokeview.  should be fixed .  let me know if you still see a problem.

**Comment by mcgratta** [comment]
Yes, it works! Thanks.
