### ISSUE TITLE
how to build dem2fds

### ISSUE THREAD

**Issue by ning-drift** [firemodels/smv#2106]
The dem2fds program appears to be still being updated.but don't include in release package. how to build it?

**Comment by ning-drift** [comment]
maybe only can install old version dem2fds. hope republish in future

**Comment by mcgratta** [comment]
Where did you find this program? What repository are you searching?

**Comment by ning-drift** [comment]
> Where did you find this program? What repository are you searching?


just install smv6.7.12 to get last support version .after this version gforney removed
dem2fds(Commit 58b66db). it's a mistake?

**Comment by mcgratta** [comment]
To my knowledge, we no longer use this program. We use [this program](https://github.com/firetools/qgis2fds) instead.

**Comment by ning-drift** [comment]
> To my knowledge, we no longer use this program. We use [this program](https://github.com/firetools/qgis2fds) instead.

thank u!this information is very useful.i will try it
