### ISSUE TITLE
smv crash with multiple customized colorbars

### ISSUE THREAD

**Issue by ChristianKraft** [firemodels/smv#211]
Hello Glenn!

Sorry, for opening this again. But smokeview still crashes, if I use customized colorbars.  
It works fine for **one** colorbar but if I add another customized colorbar it crashes again.

It is the same procedure as in [Issue #169 ](https://github.com/firemodels/smv/issues/169?_pjax=%23js-repo-pjax-container) but just for two or more then one customized colorbars.

Would you please check it again?

Please let me know if you need a more detailed description.

Christian

**Comment by gforney** [comment]
I'll take a look.

**Comment by gforney** [comment]
not able to reproduce your problem.  upload the casename.smv and casename.ini file that is failing and I"ll take a look

**Comment by ChristianKraft** [comment]
This is strange. This morning I couldn't reproduce it, too. It took twenty tries to trigger the error. After that, the error occurs more frequent.

Please find the smv and the ini file attached as zip.


![grafik](https://cloud.githubusercontent.com/assets/11407769/22726320/38fcd99c-edd3-11e6-9a83-62710852b12b.png)

![grafik](https://cloud.githubusercontent.com/assets/11407769/22726318/329d2e3a-edd3-11e6-83ec-94a8582d3c58.png)


[gr4.zip](https://github.com/firemodels/smv/files/759880/gr4.zip)

**Comment by gforney** [comment]
try smokeview located here.  I changed the way I'm allocating memory for colorbars.  The crash went away for me but then maybe I'm seeing the same random behavior you were seeing.

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing
