### ISSUE TITLE
Incorrect checksum error loading particle file

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#293]
Glenn,

I'm trying to look at Kevin's grassland flame spread case with Smokeview Test (SMV6.4.4-454-g0f3ceae).

/home4/mcgratta/firemodels_forked/fds/Validation/CSIRO_Grassland_Fires/Test/Case_C064_fine.smv

When I try to load particles I get this error:

smokeview(65261,0x7fffd48733c0) malloc: *** error for object 0x1070d1600: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

Also, note that I had to copy the case over to my account in order to run it.  This has not always been the case.  So something permission-wise has changed in SMV or on burn.  It would be convenient to be able to look at someone's case from their directory.  For large cases, the copy takes significant time.

**Comment by rmcdermo** [comment]
Note that loading HRRPUV and Smoke worked fine.

**Comment by gforney** [comment]
are you getting the error when  you run it from kevin's account or from your account?

**Comment by gforney** [comment]
The logic for deciding whether smokeview can write to a directory is not working.  (If smokeview decides it can't write to a directory which should be the case for your situation, it is supposed to write to a temp directory).  I'm investigating (no good deed goes unpunished.  this bug occurred when I added code to speed up the smokeview startup!)

**Comment by rmcdermo** [comment]
The error happens when running smv from my account after I have copied the files from Kevin's.

However, I would still like to be able to run smv from Kevin's directory.

So there are two problems:

1. SMV crashes on particle file load.

2. SMV will not run from someone else's directory. (Note I am not trying to write anything to that directory. I just want to load files.)

**Comment by gforney** [comment]
I fixed 2.  The C routine "access" for determining whether a file or directory is writeable was not working for samba (on PC) or cifs (on Mac) mounted drives.  I had to write my own routine for this.  

I'm working on 1.

**Comment by gforney** [comment]
I'm also seeing if I can speed things up

**Comment by gforney** [comment]
fyi:  making some progress.  Its failing on a linux system also.  I now know the line of code where it is failing - need to figure out why.

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

turns out in C if x is declared as an integer the following assignment statement DOES NOT set x to "zero" at east on Linux and Mac computers

x = 0.0

**Comment by gforney** [comment]
assume this issue has been fixed except possibly for slow startup which has its on issue now.  if not, let me know
