### ISSUE TITLE
Slow slice file load

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#317]
The fast slice loading was working in SMV6.4.4-454-g0f3ceae.

The current version is loading slowly.  Use this case to test.  Should load in about 1 s on mac mount, but now takes about 27 s.

/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Validation/UMD_Line_Burner/Current_Results_MaCFP_2017/propane_XO2_ramp_dx_p3125cm.smv

**Comment by gforney** [comment]
I'll take a look at it

**Comment by gforney** [comment]
randy, do you have the installer for the fast smokeview on your mac?  If so, could you put it somewhere on burn where I can get it.  thanks.

**Comment by rmcdermo** [comment]
/home4/rmcdermo/SMV6.4.4-454-g0f3ceae_osx64.sh

**Comment by gforney** [comment]
got it.  thanks

**Comment by gforney** [comment]
git bisect determines that this is the commit causing the slow down

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[e22f87fe77e67ba24cd761752d84653af26bfc48] smokeview source: use fopen instead of _access to determine if a directory is writable (_access reports wrong result for samba mounted directories in windows smokeview)

**Comment by gforney** [comment]
git bisect determines that this is the commit causing the slow down

3fdaab66b8571e852fefbf1c0909f404bcd7aeab

smokeview source: use fopen instead of access also on mac to determine if a directory is writable

**Comment by gforney** [comment]
try smokeview posted here and see if it speeds things up any.  I was calling the routine multiple times that determend whether a directory was writable, now I'm calling it only once. 

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rmcdermo** [comment]
Much better...

```
.smv Processing Times
---------------------
.smv file(net): 0.0 s
      filelist: 1.2 s
.smv file(cum): 1.2 s
         setup: 0.1 s
        pass 1: 0.0 s
        pass 2: 0.0 s
        pass 3: 0.0 s
        pass 4: 0.0 s
        pass 5: 0.0 s
all passes: 1.3 s
   wrap up: 1.4 s

processing config file: /Applications/SMV6.5.2-44-g6649dff_osx64/bin/smokeview.ini
complete
clipping off

Startup time: 3.1 s
```

**Comment by gforney** [comment]
I"m going to close this.  probably the best I can do.  let me know if this problem crops up again
