### ISSUE TITLE
Show DEVC ID in Smokeview

### ISSUE THREAD

**Issue by ChristianKraft** [firemodels/smv#384]
Hello! It would bei nice to have the possibility to show the devc id in smokeview similiar to the quantity, value and unit. 

Best regards
Christian

**Comment by gforney** [comment]
I'll take a look at it

**Comment by gforney** [comment]
try smokeview posted here (added a "ID" checkbox in the device dialog box)
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by ChristianKraft** [comment]
Thank you, Glenn. It works. I see the devic id.

**Comment by gforney** [comment]
Thanks for reporting back.
