### ISSUE TITLE
Rendering with small r does not seem to work

### ISSUE THREAD

**Issue by bphusted** [firemodels/smv#393]
Using Smokeview 6.5.4 -4-g4e1f876  on  windows 7, 64 bit.
When I render a picture using r, I get an error (unable to render file). Rendering an image using R works. When I reversed to version 6.5.3(SMV6.5.3-3-g4322120) it worked again. 
To be sure that it had noting to do with the way I installed the program, - I reinstalled 6.5.4 in the same way as 6.5.3 and the error came again.
This error also leads to that the "make movies" does not work in version 6.5.4. 

![image](https://user-images.githubusercontent.com/9365073/30379594-5450291e-9897-11e7-8016-317dca9c5780.png)

**Comment by gforney** [comment]
this has already been reported and fixed 

https://github.com/firemodels/fds/issues/5371

for a smokeview that fixes the problem see:
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by bphusted** [comment]
Ok, thanks. I will close the issue
