### ISSUE TITLE
Rendering option

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#449]
Glenn,

Would it be possible to render an image, but first get the option to name it before it's written. When I hit the 'r' keyboard, it just render image with random numbers, what I would like to see --if possible-- to get a box that I name my image before it's written. Sometimes, it's quite painful when I render multiple images, and then don't have any clue how to differentiate between them. 
I'm asking for something similar to screen capture, when you select your image width, you get an option to name your image before it's written in the desired directory.

**Comment by gforney** [comment]
Yes. Look at the dialogue box.

**Comment by sbenkorichi** [comment]
Thanks Glenn, that helped, I wasn't aware of that. 
lots of hidden treasures in smokeview.
One more thing please, when I use which frame(s): 'Current' , it will not render the image as in the prefix, but rather as the CHID. As for other options, it would render it as the prefix. 
Let me know if you require any dummy file for testing.
![rendering](https://user-images.githubusercontent.com/20113030/32170160-74e5323e-bd6b-11e7-8796-e8115e2dbc88.png)

**Comment by gforney** [comment]
it is working for me.  which version of smokeview are you using (though I have not made changes in this part of the code for a long time)

![render_test](https://user-images.githubusercontent.com/12403014/32172602-8eba782c-bd52-11e7-8eb8-f98e1457c40b.png)

**Comment by sbenkorichi** [comment]
Thanks,
ugh, you've caught me again. I've just installed FDS_6.5.3 this morning testing input file form a user in discussion group, and I completely forgot that smv was set back to previous version. 
It's working with the up to date release.
