### ISSUE TITLE
Delete key: Doesn't function inside box

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#471]
This issue has been reported in discussion group [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/lJgqKjFTroo/9YyJposWBgAJ).

**Comment by gforney** [comment]
its working for me on both linux and windows.  are you sure you downloaded the correct install?
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA

**Comment by sbenkorichi** [comment]
hmm,
This is what I have 
```
$ smv

Smokeview  Test(SMV6.6.0-50-ge8a6383) - Nov  9 2017 - 09:32:27

Version          : Test
Revision         : SMV6.6.0-50-ge8a6383
Revision Date    : Wed Nov 8 21:58:28 2017 -0500
Compilation Date : Nov  9 2017 09:32:27
Compiler         : Intel C/C++ 17.0.4
Platform         : LINUX64
```
Dialogue -----> Motion ---> scaling, 
when I try to delete the value with DELETE key for scale x it doesn't work. But, for backspace it works.

**Comment by sbenkorichi** [comment]
Well, 
here is how it works: I have to select first the numbers, then hit delete. 
I forgot the DELETE works the opposite as backspace, i.e. has to put cursor before the number.
