### ISSUE TITLE
toggle smv with cad: Fails after 2 attemps

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#472]
Glenn,
I forgot to report this issue, I've just noticed it few days ago, we were busy with the release so I left it.
While working with blender, it does generate a file that would be linked with smv after double click on q,
but after clicking again on q, it returns the view to real fds geometry view. Then, q no longer would be effective, and I have to close and reopen smv again. Let me know if you need a simple case to upload it for you.

Cheers,
Salah

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Perfect, works as a champ !
