### ISSUE TITLE
HRRPUV not loading

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#482]
Glenn, 
I've noticed that the HRRPUV doesn't load for the first time, I have to load first the smoke then reload the HRRPUV to get it working. 
Here is some extra info: 
I've tried to trace the issue, it has begun after this release (SMV 6.3.12 Git-r20-1-gbcd83cd) 

I'm working under Linux.

**Comment by sbenkorichi** [comment]
Weird, 
with other cases works fine. 
I had to look into the case (a tunnel), then found the VENT was out of the mesh, that's why it wasn't loading with current release. So, smokeview is ok.

@mcgratta 
Would it be easy to throw an error at the starting as ( input file wasn't properly set when Vents are out of domain?)

**Comment by gforney** [comment]
your going to have to upload a case.  It is working for me

**Comment by mcgratta** [comment]
We generally don't throw errors if objects are out of the domain. Two reasons---First, it would clutter the output logs, and second, each MPI process reads in only the vents within its mesh(es). To throw an error would mean doing an MPI exchange on startup, which is just one more thing that can break.

**Comment by sbenkorichi** [comment]
Glenn, yes it works after putting the vent has surf of fire inside the domain.
Kevin, That would be a bit complicated, I thought it would be the same as when Vent isn't attached to an OBST.
