### ISSUE TITLE
Movie: Delete images after file is being generated

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#483]
Glenn,
Would it be possible to pass a flag to smokeview to delete these images after the avi or mp4 ec. is created.
Like: `$ rm *.png *jpeg `

**Comment by gforney** [comment]
1.  Ioften want to keep the pngs around so I can make a different kind of movie.  2.  doing a global rm *.png would erase pngs you don't want to erase.  same for rm casename*.png . so this is best done in your your command shell.

**Comment by sbenkorichi** [comment]
Ok, thanks 
I agree it would remove all cases (which is downside of it), but one could generate first the movie before generate the casename.png. I guess, it's better to keep it in a shell script.
