### ISSUE TITLE
Problem with updating smokeview under linux

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#498]
Glenn,
there seems to be a problem with smokeview 6.6.1 when I update to it. It has some issue with the libararies.
```
$ smokeview
smokeview: error while loading shared libraries: libifport.so.5: cannot open shared object file: No such file or directory
```

Note that I'm already exporting the directories in the .bashrc. If I install when it comes with the bundle it works. But, when I try to upgrade for later version, it throws this error. I didn't look deep into this why.

**Comment by gforney** [comment]
I'll take a look

**Comment by sbenkorichi** [comment]
When I download smv 6.6.0 separably, it works but not for 6..6.1 there might be some bug not letting it setting appropriately the directory of the libraries.

**Comment by gforney** [comment]
try linux smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Fixed, but from the link shared in the other issue.
