### ISSUE TITLE
visual artifacts in slice file display

### ISSUE THREAD

**Issue by gforney** [firemodels/smv#511]
visual artifacts are appearing when two parallel slice files are displayed.  
![circular_burner_0648](https://user-images.githubusercontent.com/12403014/35350446-f6d5991c-010b-11e8-801a-99f6ca231fbb.png)

This visual is from a case with 5 horizontal meshes.   smokeview needs to display partially transparent objects from back to front.  The artifacts are occuring because the 10 slices are not being sorted in the proper order (back to front)

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

![circular_burner_0647](https://user-images.githubusercontent.com/12403014/35352443-f201b08c-0111-11e8-8650-42d776f07762.png)

**Comment by mcgratta** [comment]
Works! Thanks.
