### ISSUE TITLE
Unloading slices cause the colourbar to flip automatically

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/smv#566]
When I load a velocity slice, I flip the colour bar so that the red is on top and the blue is on bottom. However, when I unload it and load it again, the colour bar goes back to its default (blue on top and red on bottom).  

In the previous version of smokeview, the colour bar stayed flipped at all times. 

Also, the new auto flip functionality seems to have a mind of its own. It seems to flip the colour bar at random times. I still couldn't figure out how it works and there is nothing in the user guide about it.

**Comment by rmcdermo** [comment]
Have you saved the .ini file?  Please specify precisely the version of Smokeview you are using.

**Comment by adnannweilati** [comment]
Sorry. I using the latest version 6.6.3 - (build: SMV6.6.3-0-gc63bf29) February 23, 2018.
and yes I have a saved .ini file.

**Comment by sbenkorichi** [comment]
We have changed the flip default color bar only for VISIBILITY, the default now is red at bottom and blue on top to show that red is the critical. I'm using 6.6.3 and the color bar for velocity is normal.
As Randy suggested, you should remove the .ini file if you have saved it as it will keep your previous setting view.

**Comment by adnannweilati** [comment]
My colour bar setting are different than the default ones you get when you open smokeview for the first time.
![image](https://user-images.githubusercontent.com/38315126/38669170-97c23c90-3e3d-11e8-8ac6-8d409b0a2fd3.png)
![image](https://user-images.githubusercontent.com/38315126/38669251-c88ed478-3e3d-11e8-8e13-a09b9786e07d.png)

**Comment by adnannweilati** [comment]
I edited the main .ini file in the installation directory on C: drive so that every time I load smokeview I would have these colour bar settings by default
