### ISSUE TITLE
Feature request: show more than one slice in 3D slice

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#567]
Glenn, 
If this is trivial, could it be possible to show more than one slice at a time in a single direction.
Say for example you load 3D slice and in X, you have only one that you can move it, but won't be possible to be able to show two slices instead of 1? 
Thanks !

Salah

**Comment by gforney** [comment]
That would not be a trivial change plus it would be messy to implement a
method for moving them. I'll think about  how to do it but at this point
don't see an easy way to do it.

**Comment by sbenkorichi** [comment]
Ok, thanks, it's not an urgent, but it could be a good feature to have.
You can get to it once you get a chance in the future.
