### ISSUE TITLE
Load/Unload menu change

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/smv#568]
Something very minor but annoying. In all the previous versions of Smokeview, the Load/Unload menu used to start with:
3D smoke
Slice
Vector Slice

However, in Smokeview Version 6.6.3, the Load/Unload menu changed slightly so now its: 
3D smoke
Vector Slice
Slice

![image](https://user-images.githubusercontent.com/38315126/38677887-74699530-3e57-11e8-9912-9502ce924d01.png)

I found this annoying since I rarely open any vector slices so there is no point of having it directly under 3D Smoke.
In my opinion it would be much better if the user had the control to change the menu order.

**Comment by rmcdermo** [comment]
Thanks for the comment.  But this is a subjective setting.  Making this manual would be unnecessary work.

**Comment by adnannweilati** [comment]
I understand. But what was the point of changing the menu order in version 6.6.3?

**Comment by gforney** [comment]
I was correcting menus for another option (geometry slice/boundary files).  This was just a side effect of that change. If I an easily change the order back I will.  The problem though is this is a slippery slope.   Someone else might prefer boundary files to be first.   The menu order set in how it is coded - don't see how to make it user customizable.
