### ISSUE TITLE
Smokeview newer than 6.5.0 does not find slices and vector slice during startup processing for FDS 5.5.3 results

### ISSUE THREAD

**Issue by saschagottfried** [firemodels/smv#572]
Due to business needs we still use FDS 5.5.3 for some projects. This might last until year 2020. Recently we discovered that Smokeview versions newer than 6.5.0 do not render slices and vector slices. Every quantity lists a single slice "Z=0.0". Plot3D in this case works as expected. Smokeview 6.4.4 does slice rendering as expected. This is the current mitigation strategy.

The working directory was not touched by any other smokeview version prior to this observation. I made sure this is not related to issue firemodels/fds#5969. The behaviour is reproducible. Removing files like chid.binfo, chid.sinfo or chid_slice.info do not affect the observed behaviour.

I noticed a relevant change in release notes of SMV 6.5.0 about enhancements to speed up smokeview startup time. These changes might be related to my issue.

I can add all the details to reproduce the issue. Glenn, is it intended behaviour that newer Smokeview versions (> 6.5.0) have dropped support for rendering FDS slice output data generated with FDS 5.5.3 ? Is there any chance to get this issue fixed?

Running with Smokeview 6.4.4 (CHID has been obfuscated)
```
processing smokeview file: chid.smv
   pass 1 started
   pass 1 completed
   pass 2 started
   CAD geometry file: chid.ge1 could not be opened
   pass 2 completed
   pass 3 started
     Loading surface textures
       Loading colorbar texture - completed
     Surface texture loading completed
   pass 3 completed
   pass 4 started
     examining 1'th slice file
     examining 101'th slice file
     examining 201'th slice file
     examining 301'th slice file
     examining 323'th slice file
   pass 4 completed
chid.smv processing completed

beginning wrap up
  updating vector slices
    obtaining parameters from 1'st slice file
    obtaining parameters from 101'st slice file
    obtaining parameters from 201'st slice file
    obtaining parameters from 301'st slice file
    obtaining parameters from 323'st slice file
    examining 1'st slice file for vectors
    examining 101'st slice file for vectors
    examining 201'st slice file for vectors
    examining 301'st slice file for vectors
    examining 323'st slice file for vectors
    314 vector slices found
    updating vector slice menus
  vector slices update completed
```

Running with Smokeview 6.5.0

```
processing smokeview file: chid.smv
  pass 1
  pass 2
***Error: CAD geometry file: chid.ge1 could not be opened
  pass 3
  pass 4
  wrapping up
complete


.smv Processing Times
---------------------
all passes: 0.0 s

processing config file: C:\Users\udeprod_aCmHV\Downloads\smv_6.5.0_win64\smokeview.ini
complete
clipping off

Startup time: 0.6 s
```

**Comment by rmcdermo** [comment]
@saschagottfried Glenn works to maintain backward compatibility within reason and I'm sure he will see what can be done to address your issue.  But, just to play devil's advocate, why can't you simply maintain and use the older version of Smokeview that came with 5.5.3?

We are moving ahead with many aspects of the code.  In particular, getting Smokeview to work well with large, multi-mesh cases and complex geometry---not to mention getting bundles to work---takes a significant amount of Glenn's time.  In fact, he does not have enough time to work on our current pressing development issues.  So, I am not very excited about him spending time to support FDS 5.5.3.

If you really need SMV 6.6.3 to run FDS 5.5.3 results, I would appreciate it if you would do the [Git bisect](https://github.com/firemodels/fds/wiki/Git-Notes-Bisect) for Glenn to figure out exactly which commit caused the problem.  You might have to bisect both SMV and FDS and this bisect will surely span the [deprecated](https://github.com/firemodels/fds-smv_deprecated) repo.

**Comment by gforney** [comment]
try smokeview posted here.  note only the windows pc smokeview has been updated.  
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by saschagottfried** [comment]
Hi Glenn,

this looks very good to me. All slices and vector slices are displayed properly. I loaded all slices and vector slices successfully. Rendering looks good to me as well. I will forward this version to the CFD engineer that reported the issue to look at the model output in detail. By the way: this version feels blazing fast. Thank you for looking at this issue.

![load_slices_menu](https://user-images.githubusercontent.com/1422627/38916231-d9715a9c-42e6-11e8-83ee-4e9ea86ec4e9.PNG)


Smokeview - Console output (CHID and some other details have been obfuscated)

```
Smokeview  Test(SMV6.6.3-203-gcd651b4) - Apr 17 2018 - 15:39:11

Version          : Test
Revision         : SMV6.6.3-203-gcd651b4
Revision Date    : Tue Apr 17 15:37:20 2018 -0400
Compilation Date : Apr 17 2018 15:39:11
Compiler         : Intel C/C++ 18.0.2.185
Platform         : WIN64  (Intel C/C++)


Smokeview  Test(SMV6.6.3-203-gcd651b4) - Apr 17 2018 - 15:39:11

Version          : Test
Revision         : SMV6.6.3-203-gcd651b4
Revision Date    : Tue Apr 17 15:37:20 2018 -0400
Compilation Date : Apr 17 2018 15:39:11
Compiler         : Intel C/C++ 18.0.2.185
Checksum(SHA1)   : b03b23e75c014d035b86b7a459efb8eda244048c
Platform         : WIN64  (Intel C/C++)

...
Scratch directory: c:\temp\

*** This version of Smokeview is intended for review and testing ONLY. ***

initializing Glut
complete
initializing OpenGL
complete

processing object file: C:\...\SMV6.6.3-203-gcd651b4_win64\objects.svo
complete

processing smokeview file: CHID.smv
  pass 1
  pass 2
***Error: CAD geometry file: CHID.ge1 could not be opened
  pass 3
  pass 4
  wrapping up
complete


.smv Processing Times
---------------------
.smv file(net): 0.0 s
      filelist: 0.0 s
.smv file(cum): 0.0 s
         setup: 0.0 s
        pass 1: 0.0 s
        pass 2: 0.0 s
        pass 3: 0.0 s
        pass 4: 0.1 s
        pass 5: 0.0 s
all passes: 0.2 s
   wrap up: 0.0 s

processing config file: C:\...\SMV6.6.3-203-gcd651b4_win64\smokeview.ini
complete
clipping off

Startup time: 1.1 s
```

**Comment by saschagottfried** [comment]
@rmcdermo 

I mentioned a possible mitigation strategy to stick with SMV 6.4.4 and I would have accepted a "won't fix" reply. But now this seems to be fixed and I am happy that I reported the issue. Since I already know your work is very demanding and your time is precious I usually put much effort in editing issues that are either concise or detailled.

**Comment by saschagottfried** [comment]
Will this fix be released with Smokeview 6.3.4? Is this release already scheduled?

**Comment by gforney** [comment]
the latest smokeview that will be released soon does fix the problems identified in this issue.  to test again try smokeviews located here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by gforney** [comment]
Not that I am aware of

**Comment by saschagottfried** [comment]
Ok, than I post feedback for testing efforts using the version compiled at 17.4.2018. Since you already closed the issue I suppose your are pretty sure to have fixed the issue. I can only provide results from black-box testing done by a CFD engineer.

**Comment by saschagottfried** [comment]
Glenn, thank you very much for releasing version 6.6.4.

I compared some metrics of Smokeview 6.4.4, release in January 2017, and Smokeview 6.6.4 with regard to render a VELOCITY slice (X direction)  of a larger model computed with FDS 5.5.3

- speed of loading slice data from network drive
- memory consumption after loading slice
- cpu load during rendering
- frame rate during rendering (enabled GPU did not make a difference)

Differences between both versions were marginal and never more than 5 percent.
I could not find any notable differences in visual quality.

System
- Xeon E3 1270
- 16 GB RAM
- NVIDIA Quadro 600 (WHQL driver: 353.62)

Finally, I could not find this issue referenced in release notes of Smokeview 6.6.4. Could you please make it visible that this issue contributed to the latest release. I did notify my coworkers and even my boss that  contributing to an open source project creates a value both for the software product and for our company.

**Comment by gforney** [comment]
I just updated the release notes making a reference to this issue.  Our project would not be successful without contributions such as yours.  We appreciate it very much!
