### ISSUE TITLE
3D smoke ---> Temperature*

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/smv#624]
Glenn,
Quite some updates have been done from fds side outputing thing. One thing that isn't clear is what's the temperature quantity doing in the 3D smoke options?
See attached image below.
Even by trying to tick it, but nothing happens. 
And sorry if I'm not doing my home work.

![image](https://user-images.githubusercontent.com/20113030/41502046-979cfaa4-71a8-11e8-9805-27d5225ca3d9.png)

**Comment by mcgratta** [comment]
It's used as a way to color fire and smoke. Below a given temperature, smoke is black. Above it is orange, i.e. fire. This quantity should probably only be read in as a combination with other quantities.

**Comment by gforney** [comment]
Are you using a recent version of smokeview?

**Comment by sbenkorichi** [comment]
I did try to upload the SOOT/TEMPERATURE/CO2, 
![image](https://user-images.githubusercontent.com/20113030/41502474-8544f140-71b2-11e8-91fd-925ec8b3749c.png)

SOOT/HRRPUA/CO2
This is what it gives.
![image](https://user-images.githubusercontent.com/20113030/41502455-17bf6eca-71b2-11e8-8c3b-2b02e106ee43.png)

And when uploading only TEMPERATURE, then only time bar appears.

--Glenn,
smv version 
```
$ smv

Smokeview  SMV6.6.4-0-g7331116 - May 15 2018

Revision         : SMV6.6.4-0-g7331116
Revision Date    : Mon May 14 15:47:45 2018 -0400
Compilation Date : May 15 2018 07:52:22
Compiler         : Intel C/C++ 18.0.2
Platform         : LINUX64
```

simple input file that I'm working on now. 

```
&HEAD CHID='GNU'/
&TIME T_END=30.0/


&MESH ID='MESH',   IJK=20,20,24, XB=3.75,6.25,3.75,6.25,0.0,3.0/
&MESH ID='MESH01', IJK=40,15,12, XB=0.0,10.0,0.0,3.75,0.0,3.0/
&MESH ID='MESH02', IJK=40,15,12, XB=0,10.0,6.25,10.0,0.0,3.0/
&MESH ID='MESH03', IJK=15,10,12, XB=0.0,3.75,3.75,6.25,0.0,3.0/
&MESH ID='MESH04', IJK=15,10,12, XB=6.25,10.0,3.75,6.25,0.0,3.0/


&REAC ID='Propane',
      FUEL='REAC_FUEL',
      FORMULA='C3H8',
      CO_YIELD=0.01,
      SOOT_YIELD=0.01,
      HEAT_OF_COMBUSTION=5.0329E4/

&SURF ID='FIRE_1000kW',
      COLOR='RED',
      HRRPUA=1000.0,
      TAU_Q=-10.0/

&OBST ID='Wall_max_Y', XB=0.75,9.0,9.0,9.25,0.0,3.0, SURF_ID='INERT'/ 
&OBST ID='Wall_min_X', XB=0.75,1.0,0.75,9.0,0.0,3.0, SURF_ID='INERT'/ 
&OBST ID='Wall_min_Y', XB=1.0,9.25,0.75,1.0,0.0,3.0, SURF_ID='INERT'/ 
&OBST ID='Wall_max_X', XB=9.0,9.25,1.0,9.25,0.0,3.0, SURF_ID='INERT'/ 
&OBST ID='FIRE', XB=4.5,5.5,4.5,5.5,0.0,0.125, SURF_IDS='FIRE_1000kW','INERT','INERT'/ 

&HOLE ID='Hole_max_Y', XB=4.75,5.25,8.75,9.5,0.5,1.0/ 

&VENT MB='YMAX', SURF_ID='OPEN'/ 

&SLCF QUANTITY='TEMPERATURE', PBZ=2.0/
&DEVC ID='TEMP', XYZ=5,5,2.9, QUANTITY='TEMPERATURE' /
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBZ=2.0/

&TAIL /
```

**Comment by gforney** [comment]
Temperature/smoke is a recent addition not yet "mature" in smokeview, I'll
take a look.

**Comment by gforney** [comment]
try testing with the version of smokeview you downloaded today (7/2/2018) and indicate what is still not working
thanks

**Comment by sbenkorichi** [comment]
Ok,
Run the example provided above. 
Load---->3Dsmoke--->Temperature,
you will see only the time bar will appear, there is no slice or anything. 
What's the temperature quantity doing there?
How can we use it?
Kevin gave some explanation above, but I still can't get it working with other quantities, 
can you please make a demo for how to use it and check if it's doing what's meant to.

Thanks !

Salah

**Comment by mcgratta** [comment]
Temperature is not an independent quantity that can be loaded by itself. I suggest we not make a menu option for Temperature alone. It only makes sense when loaded with Soot, HRRPUA, and/or CO2.

**Comment by gforney** [comment]
Load the smokeview below.  I've cleaned up the 3d smoke dialog box.

smokeview displays 3d hrrpuv and 3d temperature files when a cutoff value is above a specified value (below that value it colors as soot if you loaded soot - it draw nothing if you didn't load soot).  Go to the 3D smoke dialog box and click on the fire tab witnin the Color/opacity panel.   Decrease the value for the temperature (C) widget.  You should see the fire.  

I think we need to keep the menus as is to enable us to view large cases.  Some times we will want to view just 3d hrrpuv or temp files without loading soot because the soot files are so large.  If you load only hrrpuv or temp, smokeview uses an opacity you specify.

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Nice, now I can see it. That clears it for me. 
I just reduced temperature to 100c and the fire appeared. 

I will leave it up to you to close. Might be worth to stay open until some documentation is done in smv guide.

Thanks !

![image](https://user-images.githubusercontent.com/20113030/42230243-620b3f14-7ee0-11e8-974f-effd92f359d1.png)
