### ISSUE TITLE
Extract data from FDS file

### ISSUE THREAD

**Issue by wangxiaosaii** [firemodels/smv#635]
How do I extract data about the velocity of smoke particles from the FDS file?

![1529992394 1](https://user-images.githubusercontent.com/34532254/41891797-6e0de9c6-7948-11e8-890e-39252c1ca389.jpg)

**Comment by rmcdermo** [comment]
In FDS, smoke follows the velocity of the gas.  Look in the user guide under SCLF (slice files) or DEVC (devices).  You can look at a QUANTITY='VELOCITY'.

What you have shown in your post are the source code files from a very old version of FDS.  These have nothing to do with extracting data from a simulation.
