### ISSUE TITLE
Make Solid only the default for GEOM

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#675]
Glenn,
Could you make this the default option in the next build?  Thanks.

![screen shot 2018-07-30 at 6 32 55 pm](https://user-images.githubusercontent.com/4418497/43427330-153f449e-9427-11e8-9c15-77248cfe7600.png)

**Comment by gforney** [comment]
done.

**Comment by gforney** [comment]
closing issue - let me know if this is still a problem
