### ISSUE TITLE
Obstacle outlines not shown in hrrpuv below cutoff

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#711]
Glenn,
Looks like the obstacle outlines are tied to whether or not you load hrrpuv for a given mesh.  See below.  The I-beam is missing.  This case can be found in
```
/home4/rmcdermo/Work/NFRL_Commissioning/TEST7_RAMP
```
![screen shot 2018-09-25 at 5 29 53 pm](https://user-images.githubusercontent.com/4418497/46044481-e020ed00-c0e8-11e8-9e7d-23e1a3801d19.png)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
I have a debug option to show outlines only when smoke or fire is present in the mesh.  this option was inadvertently set to on.  I've fixed this and will build a new smokeview when my mac is finished with an OS update (that it decided to do on its own!)

**Comment by gforney** [comment]
should be fixed in smokeview posted here

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rmcdermo** [comment]
Working now.  Thanks!
