### ISSUE TITLE
BNDF showing ambient values at mesh interfaces

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#714]
Glenn,
This case is behaving oddly.  The mesh boundaries for BNDF show ambient values, but not at the corners.  Can you play with this case, and try to figure out whether this is on the SMV or FDS side?  Thanks.

```
/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Pyrolysis/pyro3d_transport_hires.smv
```

![screen shot 2018-09-27 at 10 26 39 am](https://user-images.githubusercontent.com/4418497/46152846-d8c02780-c23f-11e8-8a46-6a4c8f4a58b0.png)

**Comment by gforney** [comment]
I'm looking at it

**Comment by rmcdermo** [comment]
Here is a simplified case that may hold a clue.  I don't see problems with BNDF at the mesh boundary, but on startup of SMV there appears to be a wall through the middle of the domain that should not be there.

/home4/rmcdermo/Issues/Issue_714/box_burn_away1.fds
