### ISSUE TITLE
Velocity vectors at nodes seem off by factor of dx/2

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#758]
Glenn,
Per our discussion.  The cases to test this problem are now up.  Look at [this case](https://github.com/firemodels/fds/blob/master/Verification/Scalar_Analytical_Solution/irrot_superbee_cos_wave_16.fds), for example.

The velocity is prescribed in FDS and I have populated UVW_GHOST correctly, based on my print outs.   The velocity field is given by u = z and w = -x.  So at the z = 0, u = 0 and the velocity should only have a vertical component.  Similarly, at the x = 0, w = 0 and the velocity should only have a horizontal component.  (This field is like a turntable spinning, solid body rotation or irrotational flow.)

Here is what we see from SMV.  Notice the slight errors in the components on the boundary.

![screen shot 2018-12-13 at 10 19 47 am](https://user-images.githubusercontent.com/4418497/49948429-716e5700-fec1-11e8-8242-f02d7193cfd5.png)

**Comment by gforney** [comment]
The attached U and W spreadsheet files are what smokeview read in at the first time step (top row in file corresponds to bottom row in smokview scene)

smokeview is expecting the data to be at the nodes not cell centers .  could it be in this case fds is outputting data obtained from cell centers?   Look at the attached u_slice spreadsheet file .  The first row contains  -0.03125.   Smokeview assumes these values are associated with 'zplt[0]'.  



[u_slice.txt](https://github.com/firemodels/smv/files/2677895/u_slice.txt)
[w_slice.txt](https://github.com/firemodels/smv/files/2677896/w_slice.txt)

**Comment by rmcdermo** [comment]
Well this is consistent with the problem we are seeing.  So, it is FDS's fault, I guess.  But I don't remember ever touching this code.

Does anyone recall touching code that would change the way a VECTOR slide is output?  If not, FDS has been this way for 10 years.

**Comment by rmcdermo** [comment]
@mcgratta Can you peer into this?  This has something to do with the logic for how U-VELOCITY is interpolated to a node versus, say, TEMPERATURE being interpolated to a node.  The logic I think goes back years.

**Comment by mcgratta** [comment]
See if this fixes it.

[https://github.com/firemodels/fds/pull/7056](https://github.com/firemodels/fds/pull/7056)

**Comment by rmcdermo** [comment]
Seems to be working.  Thanks!
![screen shot 2018-12-17 at 11 31 13 am](https://user-images.githubusercontent.com/4418497/50100892-73048b80-01ef-11e9-905b-5b0604064635.png)
