### ISSUE TITLE
CFAST mechanical ventilation visualization errors

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/smv#784]
Visualization of CFAST mechanical ventilation results seems to have two issues.

1. unlike wall and ceiling vents, mechanical vents do not indicate when the vent is closed.
2. all vents are visualized as horizontally oriented even if specified as a vertically oriented vent.

Input file that follows includes two mechanical vents, one horizontal and one vertical that open and close differently with time.  Flow visualization shows proper cutoff of flow when vent is closed but no 'X' on the vent when totally closed as is done with wall and ceiling vents.

```
&HEAD VERSION = 7300, TITLE = 'CFAST Simulation' /
 
!! Scenario Configuration 
&TIME SIMULATION = 200 PRINT = 60 SMOKEVIEW = 1 SPREADSHEET = 15 / 
&INIT PRESSURE = 101325 RELATIVE_HUMIDITY = 50 INTERIOR_TEMPERATURE = 20 EXTERIOR_TEMPERATURE = 20 /
&MISC  MAX_TIME_STEP = 2 LOWER_OXYGEN_LIMIT = 0.15 / 
 
!! Material Properties 
&MATL ID = 'CONCRETE' MATERIAL = '"Concrete, Normal Weight (6 in)"', 
      CONDUCTIVITY = 1.75 DENSITY = 2200 SPECIFIC_HEAT = 1, THICKNESS = 0.15 EMISSIVITY = 0.94 /
 
!! Compartments 
&COMP ID = 'Comp 1'
      DEPTH = 4 HEIGHT = 4 WIDTH = 4 CEILING_MATL_ID = 'CONCRETE' WALL_MATL_ID = 'CONCRETE' FLOOR_MATL_ID = 'CONCRETE'
      ORIGIN = 0, 0, 0 GRID = 50, 50, 50 /
 
!! Wall Vents
&VENT TYPE = 'WALL' ID = 'WallVent_1' COMP_IDS = 'Comp 1' 'OUTSIDE'  TOP = 1, BOTTOM = 0, WIDTH = 0.5
      FACE = 'FRONT' OFFSET = 1.75 /
 
!! Mechanical Vents
&VENT TYPE = 'MECHANICAL' ID = 'Mechanical Vent' COMP_IDS = 'OUTSIDE', 'Comp 1'
      AREAS = 0.25, 0.25 HEIGHTS = 2, 2 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.01 CUTOFFS = 200, 300 OFFSETS = 1, 1
      CRITERION = 'TIME' T = 0, 50, 52 F = 0, 1, 1 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_2' COMP_IDS = 'OUTSIDE', 'Comp 1'
      AREAS = 0.25, 0.25 HEIGHTS = 2, 2 FLOW = 0.01 CUTOFFS = 200, 300 OFFSETS = 3, 3
      CRITERION = 'TIME' T = 0, 50, 52 F = 1, 1, 0 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
```

**Comment by rpeacoc** [comment]
FYI, smv 6.7.2

**Comment by gforney** [comment]
Does HORIZONTAL refer to the flow or to the vent?  
The second mechanical &VENT line does not have an ORIENTATIONS keyword.  What is the default?

**Comment by gforney** [comment]
this is what cfast is outputting for the two mechanical vents
MVENTPOS
   1  0.7500E+00  0.1250E+01  0.7500E+00  0.1250E+01  0.2000E+01  0.2000E+01
MVENTPOS
   1  0.2750E+01  0.3250E+01  0.2750E+01  0.3250E+01  0.2000E+01  0.2000E+01


notice that the two z levels are the same for both vents.  It looks like get_vent_info has an option to get mechanical vent info for both vertical and horizontal orientations.  It must be called the same way for both cases.  Look at the .in file - are you sure that one mechanical vent is horizontal and the other is vertical (I don't see an orientation keyword for the 2nd mechanical vent).

**Comment by gforney** [comment]
I added ORIENTATION=VERTICAL, VERTICAL to the 2nd mechanical vent line and am getting the right vent visualization (see attached)

![case_0047](https://user-images.githubusercontent.com/12403014/52009847-e7467600-24a1-11e9-874f-caad4d77e0fe.png)

**Comment by gforney** [comment]
1.  mechancical vent fractional areas are always passed to smokeview as 1.0 .  If 0.0 is ever passed, an X should be drawn as with regular vents ie mechanical vents do not close the way regular vents do
2. this was a problem with cfast defaults on the &VENT line which have been fixed
