### ISSUE TITLE
Smoke View fails to open

### ISSUE THREAD

**Issue by JacobSherwin** [firemodels/smv#789]
Hi,

 I am running a car park CO model, I have run the simulation however when I try to open smoke view it fails to do so. It displays the error 

*** Error: The texture file hrrpuv was not found

As seen in the attached image.

I have also attached the FDS file, the out file and the smv file to help with any fault finding.      
![co model smoke view](https://user-images.githubusercontent.com/47205082/52188585-c9a15400-2887-11e9-888b-9a40a91cab42.png)

[OCQ1.zip](https://github.com/firemodels/smv/files/2826664/OCQ1.zip)

Jacob.

**Comment by gforney** [comment]
Thanks for starting an issue. I'll take a look.

**Comment by gforney** [comment]
The input file along with the .ge1 geometry file I presume the texture file were generated by pyrosim.  You need to copy these files from the directory where pyrosim generated them.  Contact thunderhead engineering if you need more help with this.

**Comment by JacobSherwin** [comment]
Hi, 
I have managed to fix up the CAD error regarding the ge1 file (copying it from the directory) but I still  have an issue with the texture file (displays *** Error: The texture file hrrpuv was not found) . I am unsure what you meant with the texture files and copying it from the directory? I generated the model through Pyrosim however we ran the FDS solution externally. Any clarity on where do go from here to would be much appreciated.     
Cheers,
Jacob.

**Comment by gforney** [comment]
your .smv file is messed up.  The following lines are from the .smv file you attached (in the .zip file). 
 Notice that SMOKF3D DOES NOT begin on a new line.  Smokeview thinks that this is part of the SURFACE data so it confuses hrrpuv with a texture.  You will need to rerun your case

SURFACE
 MIRROR                                                 SMOKF3D     1
 OCQ1_0001_02.s3d
 HRRPUV
 hrrpuv
 kW
