### ISSUE TITLE
Adding more decimal places to the colorbar labels

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/smv#795]
Is it possible to add more significant figures or decimal places to the colorbar labels? This is very useful when loading pressure slices as the values are usually in x10^5 so only the first 3 values are shown in the colorbar.

**Comment by gforney** [comment]
I will take a look . The difficulty is screen real estate - not a lot of
room especially when you have more than one color bar. I would suggest you
output relative pressure ( I think that quantity exists)

**Comment by gforney** [comment]
this issue fell through the cracks - took a look at it today.  try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

you can add more digits by going to Dialogs>Data>Coloring menu item and changing the "max decimals" field.  

this is implemented for slice file and boundary file colorbar labels.  

upload an input file if this doesn't solve the problem
