### ISSUE TITLE
Smokeview Crashing on Launch

### ISSUE THREAD

**Issue by AdamCowlard** [firemodels/smv#810]
I appear to have developed an issue launching Smokeview on my windows laptop. The program appears to crash as it is launching. When I double-click on a Smokeview file, it launches a dialogue window which displays text down to : 

Startup time: 0.4 s
research mode on

It then launches the visualisation window which then crashes, along with the dialogue window, before any visualisation has appeared. 

When I was using the program 6 months or so ago it was working fine which makes me think that the issue is coming from outside of Smokeview (windows update?). I have tried the following with no change:  

	• Rebooting the laptop
	• Opening both FDS and CFAST generated files that previously worked
	• Reinstalling the version of FDS and Smokeview that I was using last year
	• Upgrading to the latest release of FDS and Smokeview

I am running Windows 10 Pro on a Surface Pro 5. Please let me know if there is any other information that would be useful. Thanks in advance for any help!

**Comment by gforney** [comment]
What version of smokeview are you using? Upload your .smv file and I'll
take a look at it.

**Comment by AdamCowlard** [comment]
I'm using Smokeview 6.7.6. Do I need to change the file extension to upload it? I'm getting a message saying that Github don't support that filetype...? I can upload as a text file if need be.

**Comment by gforney** [comment]
Uploading as a text file will be fine. Also upload the .fds file.  Thanks

**Comment by AdamCowlard** [comment]
fds file is base.txt
Smokeview file is base_model.txt

[base.txt](https://github.com/firemodels/smv/files/3045032/base.txt)
[base_model.txt](https://github.com/firemodels/smv/files/3045033/base_model.txt)

**Comment by AdamCowlard** [comment]
Files attached previously are the beginning of a setup that I just started. Files below are a simple test case I ran previously that have exactly the same issue. Just in case it helps with the diagnosis!

[test_1.txt](https://github.com/firemodels/smv/files/3045050/test_1.txt)
[Test_1-smk.txt](https://github.com/firemodels/smv/files/3045051/Test_1-smk.txt)

**Comment by gforney** [comment]
Thanks. I'll take a look at it tonight.

**Comment by gforney** [comment]
I'm not yet able to reproduce the problem.  Try running smokeview that you used 6 months ago.  Does this work or crash?

**Comment by AdamCowlard** [comment]
That was the first thing I did. I had not touched the installation since last year so was surprised when it repeatedly crashed. To test if it was the new smv file, I tried to open an old smv file that ran fine previously and it still crashed. I reinstalled the original version of FDS+Smokeview and tried again with no improvement in the problem. I installed the latest FDS + Smokeview install and still have the same problem. This is what makes me think that the problem is not with Smokeview or even the smv file but rather my machine. I saw a thread for MAC suggesting that the OS upgrade was an issue and I know that Windows 10 has received numerous upgrades in the last 6 months.

In any event, I have reinstalled the previous version of the software and still have the same crash. What I haven't done is directly uninstall Smokeview. I have been installing the new version of FDS+Smokeview over the top. I can uninstall FDS using the uninstall file but there doesn't seem to be a similar process for Smokeview? Is there a clean way to remove it and reinstall from scratch?

Thanks for your time on this.

**Comment by gforney** [comment]
Follow up . If smokeview was working and now viewing same case it crashes
the problem is most likely not smokeview. Do you have Intel compilers
installed on this computer? And if so has the compilers changed since
running smokeview?

**Comment by AdamCowlard** [comment]
Sorry for the delay in response. I did some digging but wasn't able to
isolate whatever on my PC was causing it to crash. However, a new batch of
updates for Windows just came through and this seems to have fixed the
issue! Thanks for your time and help with this, very much appreciated!

Adam

*ADAM COWLARD  *| PhD MEng
Director

[image: www.taec.engineering] <http://www.taec.engineering/>
*TORERO, ABECASSIS EMPIS and COWLARD LTD*
Campbell Dallas, Westfield Park, Dalkeith, EH22 3FB, UK
*TEL* +351 912 427 648
www.taec.engineering
