### ISSUE TITLE
Cannot set data bounds for zone fire visualization in OSX version

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/smv#852]
If you open the Data Bounds dialog in the OSX version of smokeview and try to set the min or max, the dialog simply reverts back to the global radio button.

Smokeview  Test(SMV6.7.8-58-gf15a89982) - Aug 30 2019 - 10:16:59

**Comment by gforney** [comment]
try smokeview here (don't think it will work but it is the latest version)
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

if it still fails, try erasing .ini file and try again.
can you upload an input and .ini file
