### ISSUE TITLE
CFAST target temperatures do not visualize in color

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/smv#865]
[WTC.zip](https://github.com/firemodels/smv/files/3653485/WTC.zip)
Targets in CFAST should visualize with representative temperature colors.  In 6.7.9, they just show up as grey as in old versions.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
were you expecting targets to be colored by temperature or colored by input file spec? was it working in an earlier version of smokview?

**Comment by rpeacoc** [comment]
It worked in an earlier version and was colored by target temperature included in the _zone file and linked in the _smv file

**Comment by gforney** [comment]
should be fixed in smokeview posted here. 

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rpeacoc** [comment]
Tested several cases and it works fine. Closing issue.
