### ISSUE TITLE
ISOF inconsistent with SLCF

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#880]
Glenn,
The case is run in:
/home4/rmcdermo/Work/NASA_Burning_Rate_Emulator/Current_Results/BRE_Test_3_2D*

I am seeing ISOF off by a factor of 2 compared to cell centered SCLF data.

**Comment by gforney** [comment]
I'll take a look.  maybe I'm putting the wrong data into the 3D array used to generate the isosurface.  think that is the first place to look.

**Comment by gforney** [comment]
I'm seeing the same problem, also see it with node centered slice files.  looking for a division by 2 error

**Comment by gforney** [comment]
update your fds repo.  should be fixed.  let's talk tomorrow.  I think if we can put proper values into ghost cells isosurface will look better near the edge of the domain.

**Comment by rmcdermo** [comment]
Thanks.  Yes, I noticed that too, but wanted to get the main issue sorted first.  Actually, if we just mirror values into all ghost cells (J direction too) that should have fixed things as the interpolations would have been ok then.

**Comment by gforney** [comment]
let me know if you mirror the ghost cells - don't think my fix will be necessary then (my fix was to ignore J ghost cells)

**Comment by rmcdermo** [comment]
I pushed changes to FDS to mirror the values to ghost cells.  So, I don't know if you were doing anything addition in SMV, but you can revert that if so.  Thanks.
