### ISSUE TITLE
Precision of GVEC for microgravity

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#885]
Glenn,
In the attached input file when the GVEC(3) goes from -1E-04 to 1E-05 the SMV image flips on its side.  If GVEC(3)=0, the image is again correct.  I suspect there is a precision issue in the logic.
[BRE50_Test_1_1mm.fds.txt](https://github.com/firemodels/smv/files/3825994/BRE50_Test_1_1mm.fds.txt)

Here is the result with GVEC(3)= -1E-05 (incorrect):
![Screen Shot 2019-11-08 at 2 40 36 PM](https://user-images.githubusercontent.com/4418497/68505735-f844c480-0235-11ea-9961-84095a89078f.png)

Here is the result with GVEC(3)= -1E-04 (correct):
![Screen Shot 2019-11-08 at 2 41 36 PM](https://user-images.githubusercontent.com/4418497/68505758-0692e080-0236-11ea-9869-d5b5c27fa6e6.png)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
I haven't identified the problem but a work around until I do is to 
1. open up Motion/View/Render dialog box
2. open Motion tab then click on Orientation
3. click on "z vector up" button
4. click on Save settings button
It should then open up correctly from now on.  Clicking on Gravity vector down button should have worked - need to figure out why it didn't

**Comment by gforney** [comment]
try smokeview here.  I was computing an elevation and azimuth angle from the g vector.  I needed to normalize it before doing the trig - the trig functions didn't like the small numbers

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rmcdermo** [comment]
Looks like you bundled the wrong exe again.
![Screen Shot 2019-11-08 at 3 52 41 PM](https://user-images.githubusercontent.com/4418497/68509828-e831e280-023f-11ea-8ed8-993ca35833a5.png)

**Comment by rmcdermo** [comment]
Works now.  Thanks
