### ISSUE TITLE
CFAST Visualization shows mechanical vent flow and closed vent at the same time.

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/smv#952]
When visualizing a CFAST test case with mechanical ventilation, Smokeview 6.7.13 shows mechanical vents as closed even when it also shows flow through the vents.  Test case attached.

[TestCase.zip](https://github.com/firemodels/smv/files/4288917/TestCase.zip)

**Comment by gforney** [comment]
I'll take a look

**Comment by rpeacoc** [comment]
Fixed with a change to CFAST
